### ISSUE TITLE
Can the HTML5 video tag stream live video now?

### ISSUE THREAD

**Issue by yipingshui** [mbebenita/Broadway#11]
Hi mbebenita ,
   I known that the HTML5 video tag is very excellent for static video files. but I don't known whether the HTML5 video tag can be used to stream live video now?
Waiting for your help!
Thanks!!!

**Comment by soliton4** [comment]
@yipingshui the html5 video tag has a inherent latency problem.
i was only able to stream real life video using this.
with video tag i had at least 10 sec of latency. after a lot of optimization.

if you are satisfied with the answers pls close the issue

thank you

**Comment by soliton4** [comment]
@yipingshui hasnt been seen in github for a long long time

so i just close this
