### ISSUE TITLE
Do not publish mp4 files into master branch

### ISSUE THREAD

**Issue by emersion** [mbebenita/Broadway#112]
Checking out Broadway is not fast because there are mp4 files published in the master branch.

Only keep them in the `gh-pages` branch and remove them from `master`.

**Comment by soliton4** [comment]
the size of the cloning would not be reduced if we removed the mp4.
it might be neccessary for future demos to upload even more video data.

if you need a git clone optimized version of broadway i recommend you open a pseudo fork.

**Comment by emersion** [comment]
You can keep mp4 files in the `gh-pages` branch, and do not keep them in `master`. This won't break demos.
