### ISSUE TITLE
anybody using libx264?

### ISSUE THREAD

**Issue by wenxingxing** [mbebenita/Broadway#114]
i'm using libx264 in c++  to compress the video from the webcam, and now i can get the bit-stream to the browser. but the decoder don't work, i'm not sure how to configure the x264 exactly.

So is there any way to figure out why the encoding is failing?

i tried this to disable the weighted p frame, and cabac encoding, i'm not sure if it's right
```c
  param.analyse.i_weighted_pred = X264_WEIGHTP_NONE;
  param.b_cabac = 0;
```

this is the bytearray i got from the websocket, i cut the first 4 number, [0, 0, 0, 1]
![decode](https://cloud.githubusercontent.com/assets/9295126/13676887/92b9ba6c-e722-11e5-8e25-b4ac14c0a9bf.png)

onPictureDecoded was never called... Heartbroken.

**Comment by soliton4** [comment]
make sure you use base profile

**Comment by wenxingxing** [comment]
thanks, it all works!!
with this
```c++
x264_param_apply_profile(&ctx->param, "baseline");
```

it's amazing!

**Comment by soliton4** [comment]
@wenxingxing i know ;)
