### ISSUE TITLE
Error: Uncaught TypeError: Cannot read property 'avcC' of undefined

### ISSUE THREAD

**Issue by mr-dignitty** [mbebenita/Broadway#117]
- Grabbed the project zip from: https://github.com/cometas/Broadway
- opened "demo.html"
- changed the path for "video.mp4" to the path for my mp4 video
- **Browser console error says:**

`Uncaught TypeError: Cannot read property 'avcC' of undefined  @      broadwayPlayer-min.js:9 `

`constructor.play	@	broadwayPlayer-min.js:9`
`(anonymous function)	@	broadwayPlayer-min.js:9`
`xhr.onreadystatechange	@	broadwayPlayer-min.js:9`

**Lines printed in the console previous to the error are as follows:**

`stderr: increasing TOTAL_MEMORY to 67108864 to be compliant with the asm.js spec @ broadwayPlayer-min.js:1 `
`stderr: pre-main prep time: 5 ms @ broadwayPlayer-min.js:1` 
`MP4Player::readAll() @ broadwayPlayer-min.js:9 `
`Parsed stream in 8 ms @ broadwayPlayer-min.js:9 `
`MP4Player::readAll(), length: 17213855 @ broadwayPlayer-min.js:9`

**Comment by soliton4** [comment]
have you considered opening the issue at the repository where it occurs?
