### ISSUE TITLE
Unminified js

### ISSUE THREAD

**Issue by sterpe** [mbebenita/Broadway#12]
Hey Michael,

Awesome work, but noticed after forking that a couple of the js (avc-codec.js, maybe others) files were minified,  Any chance we can get the unminified source into the repository? Will make it easier for others to make work on this awesome proj.

Steve

**Comment by soliton4** [comment]
@sterpe 
@BenjaminXiao 
@BrendanEich 
maybe this interests you
https://github.com/mbebenita/Broadway/pull/44

**Comment by soliton4** [comment]
is there any reason to keep this issue open?
is anyone still waiting for a reply? i am trying to reduce the open issues to a managable amount

**Comment by sterpe** [comment]
Fine to close

**Comment by soliton4** [comment]
i just love to see the issue cnt go down ;)

ty
