### ISSUE TITLE
I run it. but the page did't show anything . how to use the demo to show video on the page?

### ISSUE THREAD

**Issue by martin823823** [mbebenita/Broadway#121]
macdeMacBook-Pro:BroadwayStream-master mac$ node index.js --port 3000
using: /Users/mac/Downloads/BroadwayStream-master/app/ as: /app
using: /Users/mac/Downloads/BroadwayStream-master/Broadway/ as: /Broadway
Session:  undefined
{ connection: 
   { session: [Circular],
     localFrames: {},
     restrictLocalFrames: true },
  setAuth: [Function] }

**Comment by soliton4** [comment]
please discuss issues about BroadwayStream at the issues page of the project
https://github.com/soliton4/BroadwayStream
