### ISSUE TITLE
h264 licensing. MPEG-LA will find you.

### ISSUE THREAD

**Issue by koush** [mbebenita/Broadway#124]
Great project. But be wary. If you use this, the MPEG-LA will come after you if your app gets big enough.

https://plus.google.com/u/0/110558071969009568835/posts/717zTopZSWf

You may want to note this in the README.

**Comment by visionscaper** [comment]
Comments thread on Hacker news : https://news.ycombinator.com/item?id=11693185

Didn't dive into the details myself yet, but I'm wondering what can be done about this? Would be such a shame if we couldn't use this wonderful project in a business setting.

**Comment by mbebenita** [comment]
@koush  That's unfortunate. I guess it was bound to happen. 

@visionscaper I don't think there is much that can be done about this, other than switching to a royalty free codec. Looking forward to https://aomedia.googlesource.com/aom/

**Comment by koush** [comment]
Chrome has PP::VideoDecoder, which is what I've switched to.

https://developer.chrome.com/native-client/pepper_dev/cpp/classpp_1_1_video_decoder

**Comment by vans163** [comment]
The fees are pretty cheap. http://www.zdnet.com/article/h-264-patents-how-much-do-they-really-cost/. I don't think this should be a concern to anyone using Broadway.js in production.  

@koush your 20 cent issue seems to stem from the second case sold to end users. If vysio is a free app it's not sold. I'm no patent lawyer but I'm sure that just reencorporating as vysio2 would reset the counter of 100k royalty free.

**Comment by koush** [comment]
@vans163 20 cents per user is not insignificant when you have even half a million users. That's $80k USD right there.

Doesn't matter if the app is free or paid. If you ship the decoder as part of your downloadable package, you are on the hook for the license.

**Comment by soliton4** [comment]
i dont think this thread is leading anywhere
