### ISSUE TITLE
YUVCanvas.drawNextOutputPicture calls drawNextOuptutPictureGL in wrong way

### ISSUE THREAD

**Issue by yuba** [mbebenita/Broadway#125]
YUVCanvas.js

drawNextOuptutPictureGL method requires only one parameter which has properties {yData, uData, vData},
but drawNextOutputPicture calls drawNextOuptutPictureGL with parameters (width, height, croppingParams, data).

**Comment by soliton4** [comment]
its jut passing on the parameters to the correct function.
it works as intended
