### ISSUE TITLE
How do i have to send the data? 

### ISSUE THREAD

**Issue by g33kz0rd** [mbebenita/Broadway#127]
How does the server have to send the data?

Im currently opening it with a mp4reader and sending the raw frames that it provides me ( not jpeg or anything, just the h264 frames ) but it doesnt work

By the little knowledge I have I asume its becouse the player is not properly initialized ( with the sps and pps ) but I have little to know idea how to achieve that using the provided framework 

Im using this to decode the frames

`var player = new Player({
        useWorker: true,
        workerFile: "Decoder.js",
        width:1280,
        height:720
      });
player.decode(bytes);`

**Comment by soliton4** [comment]
please stop spaming
