### ISSUE TITLE
use Player to render h264 stream, maybe rending part right 

### ISSUE THREAD

**Issue by nepaul** [mbebenita/Broadway#129]
Just like below:
![Alt text](http://7xja18.com1.z0.glb.clouddn.com/xxxxxxxxxxxx7.png)

**Comment by soliton4** [comment]
yes

**Comment by nepaul** [comment]
@soliton4 do u know how to fix it?

**Comment by nepaul** [comment]
I use Broadway just like the BroadwayStream

**Comment by soliton4** [comment]
looks like a green rectangle to me.
i can also make out some resemblence of a circle.

**Comment by nepaul** [comment]
I concat the stream data to entire NAL  units, then transfer to Player. decode.
And it work!
