### ISSUE TITLE
Support for mkv?

### ISSUE THREAD

**Issue by amilajack** [mbebenita/Broadway#131]
Does this support only mp4 or other container formats, such as mkv?

**Comment by soliton4** [comment]
supported is so far pure h264 - annexb in base level

the mp4 parser is just to show a demo. 

i would love to integrate some file format parsers. could you contribute some?

**Comment by amilajack** [comment]
I would love to but I dont have that much knowledge of C++ or video container formats. Maybe compiling vlc to asm.js or WASM would be a start?

**Comment by amilajack** [comment]
What is the difference between the mp4.js and decoder.js files?

**Comment by soliton4** [comment]
well as you can see by looking at the content of the mentioned files they contain quite different pieces of code.

the mp4.js file contains among other routines and algorithms, a parser for mp4 files.

the decoder.js file has a variety of functions ans algorithms. most noticeable the ability to decode h264 data.

is there any specific difference you would like to be pointed out?

**Comment by amilajack** [comment]
I want to add support for other codecs, including mkv. Currently, [codecbox.js](https://github.com/duanyao/codecbox.js) supports [many codecs](https://github.com/duanyao/codecbox.js/blob/master/Gruntfile.js). I wonder if parts of it could be integrated into this project to offer more codecs.

**Comment by amilajack** [comment]
Also what does the mp4.js parser return?
