### ISSUE TITLE
Controlling FPS?

### ISSUE THREAD

**Issue by Zaithe** [mbebenita/Broadway#135]
I don't see any documentation or clear answers on the previous issues bringing this up. Some mentioned using set interval vaguely but i have put it about anywhere i can think of with no luck. Can someone elaborate how they accomplished locking in a set framerate? I don't really care if the FPS is hard coded in rather than reading it from the mp4 header. In my case simpler is better as i do not have much time.

**Comment by soliton4** [comment]
hey @Zaithe 
i think the simplest quick and dirty hack would be to do the rendering in a setInterval callback

or create a requestAnimationFrame loop and check the time. whenever its time to render the next frame you display it.

**Comment by Zaithe** [comment]
@soliton4 would you be able to show an example? Like i said i tried to put it about anywhere i could think of with no luck. 

If i was to try the requestAnimationFrame loop where would i put it? Also do you have an example of that?

**Comment by Zaithe** [comment]
I figured this out.
