### ISSUE TITLE
Struggling to get SPS data to get VUI Parameters.

### ISSUE THREAD

**Issue by Zaithe** [mbebenita/Broadway#136]
There are a lot of useful functions in AVC that i can no longer see due to them being minified. Mainly i need access to the VUI data set which can be found in h264bsd_seq_param_set.c . I would like to be able to have access to data needed to calculate misc stuff such as video width, height and fps. I traced out the data in avc.sps in mp4.js but it didn't make any sense to me. 
![image](https://cloud.githubusercontent.com/assets/2839791/17612071/5fcf56f8-6002-11e6-8588-0230d17bb7f3.png)

I thought it was supposed to be like this:
![image](https://cloud.githubusercontent.com/assets/2839791/17612102/bcb3df24-6002-11e6-8a87-6c5ad13d77d4.png)

![image](https://cloud.githubusercontent.com/assets/2839791/17612096/b0342358-6002-11e6-852b-09bb0c42dfa2.png)

Here are some good articles about calculating fps and ect from the sps data.
https://cardinalpeak.com/blog/the-h-264-sequence-parameter-set/
http://forum.doom9.org/showthread.php?t=147672

**Comment by Zaithe** [comment]
This problem has been resolved. closing topic.

**Comment by dustinkerstein** [comment]
@Zaithe, did you figure out how to parse the aspect ratio info? If you could provide any tips that would be great. Thanks!

**Comment by Zaithe** [comment]
> @Zaithe, did you figure out how to parse the aspect ratio info? If you could provide any tips that would be great. Thanks!

Sorry its been so long since i've worked on this i wouldn't know where to begin.
