### ISSUE TITLE
There has an error, when globle.Module is not null.

### ISSUE THREAD

**Issue by DavidLvSinonet** [mbebenita/Broadway#138]
Hi,
There has an error in Player/Decoder.js, line 82,
`var resultModule = global.Module || Module;`
if `global.Module` is not null, then resultModule will return the window.Module object.

It should be return `Module` object.

**Comment by soliton4** [comment]
yeah its a relic from the time when broadway wasnt using unified module headers.
any proposal how to do it instead?

ps: best to use Decoder.js as a worker anyway

**Comment by soliton4** [comment]
should be fixed in latest version
can you give it a try? @DavidLvSinonet
