### ISSUE TITLE
Cannot create more than one instance of Avc object

### ISSUE THREAD

**Issue by BenjaminXiao** [mbebenita/Broadway#14]
Every time I create more than one Avc object and then try to pass video data to it, the Javascript console spits out an error that says:

    Uncaught RangeError: Maximum call stack size exceeded
        OptimizedFilterVerLumaEdge
        OptimizedFilterVerLumaEdge

I want to be able to decode multiple video streams at once within the same webpage. Is there a better way to do this?

**Comment by soliton4** [comment]
i generally recommend using worker threads
your app will be more responsive and the video should actually render faster
at least if you are using this:
https://github.com/mbebenita/Broadway/pull/43

i will integrate it into master soon

**Comment by soliton4** [comment]
https://github.com/mbebenita/Broadway/commit/cc24730c40033fe590275a9e671498ae2d44cc64
introduces a fast and working worker  
(pun intended)
