### ISSUE TITLE
how to play raw-h264 stream

### ISSUE THREAD

**Issue by zgy520** [mbebenita/Broadway#140]
Hi, i want to play raw-h264 stream in browser, now i can get it in js by websocket, but i don't know how to play it, i know broadway can do it, but i don't know how to do it, can you give me some suggesstion?
i can get every frame of video in the form of raw-h264 stream, but don't know how to play it!

**Comment by soliton4** [comment]
there is an example on my github.
https://github.com/soliton4/BroadwayStream
it does exactly what you want to do

**Comment by zgy520** [comment]
@soliton4 the example need a video file not raw-h264 stream, i know how to handle video file but don't know how to handle video stream. i can receive h264 stream frame by frame, but don't know how to play it?

**Comment by zgy520** [comment]
@soliton4 Hi，i download the example, and modify port and file path, but when i run, there is a problem! the error as following:
![bc](https://cloud.githubusercontent.com/assets/6573014/21299056/d21bf618-c5d2-11e6-8f87-3281070273c9.png)
the picture comes from the console, and the following picture from browser debug console:
![bc2](https://cloud.githubusercontent.com/assets/6573014/21299064/e4ac5142-c5d2-11e6-89f8-efae72f4fc41.png)
ohterwise, i transfer stream via java websocket not socket.io, now ,i can't continue it, can you give me a suggesstion?

**Comment by nepaul** [comment]
**ENOENT**!
Make sure that **ffmpeg** has been installed.

**Comment by zgy520** [comment]
thank your very much! i have installed ffmpeg and then the video file i specified have played! but now ,i want to play raw-h264 stream not a video file, can you give me some suggestion? thank you!

**Comment by soliton4** [comment]
@zgy520  ffmpeg conversts whatever file you give it to a raw h264 stream. im afraid you will have to actually look at the code

https://github.com/soliton4/BroadwayStream/blob/master/app/connected.pland#L27

https://github.com/soliton4/BroadwayStream/blob/master/app/server.pland#L46

**Comment by zgy520** [comment]
@soliton4 yes, i know, i can use ffmpeg converts video file to a raw h264 stream and then play it! but now, i have no video file, what i have is a raw h264 stream, i want to play it directly! but the example you recommend me need a file, if there is a solution to play h264 stream directly other than a file? 
thank you

**Comment by soliton4** [comment]
so the example converts a video file to a raw h264 video stream, then plays it

you have a raw h264 video stream and you want to play it

why is the example not telling you everything you want?

**Comment by zgy520** [comment]
@soliton4 yes, i know your meaning! the example tell me everything i want, i have konwn broadway can play h264 video stream. but now ,i want to play h264 directly, i want to modify this example and then make it can play h264 video directly, but i don't know how to handle it. can you give me some suggestion for this popurse?

**Comment by soliton4** [comment]
@zgy520 i dont know what you mean

**Comment by zgy520** [comment]
@soliton4 what i mean is "play raw h264 stream directly in browser", but i don't know how to do it!

**Comment by soliton4** [comment]
https://github.com/soliton4/BroadwayStream/blob/master/app/connected.pland#L27

in this line the raw video stream is given to broadway to play.
do the same in your project.

**Comment by zgy520** [comment]
@soliton4 thank you! i have changed var bin = toUint8Array(parDataStr); to 
var bin = toUint8Array("ws://localhost:8877/WebApplication1/test")
but there still no video played!
if there are some things to noticed?

**Comment by soliton4** [comment]
@zgy520 have you considered the possibility that your javascript skills might be in need of some improvement.
while broadway.js is aimed to be used as out of the box as possible, it relies on the user actually having some experience in using javascript.

**Comment by zgy520** [comment]
@soliton4 thans your advice, my experience in using javascript really poor, but i would improve it as soon as possibly! thank you very much!
but now, i changed the code , the video can not play, the following is my h264 stream, can you help me confirm weather the stream is suitable or not,
0000000161e1c033c031b00320000078000000000000000000000000013200fffbd0f3e6df8b9fb1d1f77cad47d7e26ffdbff6ff57d379e721fbdfb93ef7fbeeb7d89bfbef3be7bb7fcfbbafe67ffe2f3e23f39235197b8bbd47263d737d78d85befe2c3e67a87f139cf5ce8dfb9debfeff2ad369b0791f5f7e29a6e4d2e7cef2f34c10320000078000000000000000000000000013200e4963dc2c6ff7f9283deff8bedb7e67ffcadf30e23fc9db50f7f5862c5f8c492bd7f083ae05cc4e7dfe2c38b26f716f1c5eeb893a185cf5990ee3daf83f8ff39e6e2ffefb525a18b9cbfc084ecdcc5dd66dc1ff6fe44ebdeff2d5f731ef4ff9defbebbf70320000078000000000000000000000000013200bb6ffe6ff9dcdbc17fe8bf8ee0fff794e8227abfbd8bff7fd6feffff75e6ff7fbff5e63c6c836df1fceb42cb26df67fcff2f5fe75bfe083be340f6df3ff7f1b1267e87aff3ffde8bfabfef5fd02102e665635f36ff7edf12fafe5cfbdf39e7dd7bad8bb6032000007800000000000000000000000001320046ecfdb90ebfef6fcbff5dff6a04e7dde31fc2b745fb1f700f1fefd22fe97df7614bff1ef3a137e97c7b7f09d1bb7ffdffbfbc6fd37f15dd0fdef1ffffff9b4bff9febfcfdf73febffbbf75a7beefbe7b5f4b0f9c7df87de6f3edfefad35199f6badc7f003200000780000000000000000000000000132005c737b42e682ebffbbe75efbffebd9dfdf9249ef3f7ffe3fff1ceff2fbb763137189fe7d7cfcf9f7e1dbce0f365beb4f7af0f6fbf17fcfb9e8ffbfd6dfffdfb5e6c1ff4fc9ffdc738d83e9ff72dd51267aef8c721fdf0eb237c91f9feefbdebd64c2f7fe

**Comment by zgy520** [comment]
@soliton4 Hi, i have a problem now, i hope you can help me! the problem is i can run the example correctly, but when i try to replace the video with raw-264 stream, i encounter problem, i have saw connected.js and server.js files,  but i can not associate the two files, i dont know where to call my websocket and how to send my raw-264 stream to decode function? can you help me solving this problem?

**Comment by krishongithub** [comment]
@zgy520 , did get it working? I am in need of the same now..

**Comment by sxlgkxk** [comment]
I am also the same, my video is UDP transmission / MPEG-TS encapsulation / video encoding is h264. 
I obtained the h264 part of each network packet. 
I thought it was simple: 1. use <script src="broadway.js"></script> 2. Create a new player object 3. Feeding the h264 data to the player object constantly 
Now it seems that this is not the case

Maybe I really need to improve the javascript skills, and I can only find a solution after I understand this repo ...
