### ISSUE TITLE
The video height can't bigger than 640?

### ISSUE THREAD

**Issue by kareluo** [mbebenita/Broadway#146]
It can't player normally when video's height bigger than 640, and width all is well. why?

**Comment by soliton4** [comment]
i dont know. i can play videos with 2500x1400 fine

**Comment by kareluo** [comment]
This is a screen record video, the video's height is bigger than 640, can you find some thing wrong with it ?
<img width="559" alt="qq20170416-201320 2x" src="https://cloud.githubusercontent.com/assets/7830310/25160376/4f726ee8-24e8-11e7-95f0-8258766cf1b7.png">

**Comment by soliton4** [comment]
this looks like you are feeding incomplete nal units to the decoder.
if you have a annex-b stream split it at 00 00 00 01
this sequence is the start of a nal unit.

i probably should provide some nal unit splitting code since this question keeps recuring
