### ISSUE TITLE
Decoding two videos side by side as a single video

### ISSUE THREAD

**Issue by 21praveen** [mbebenita/Broadway#148]
Hi,
I want to decode two videos side by side as a single video to synchronize them perfectly. Is it possible to do it through broadway?

**Comment by mbebenita** [comment]
Should be possible, I believe Broadway gives you back a frame at a time, so you can roll out your own synchronization code.

**Comment by 21praveen** [comment]
Is there an api to get frame number/time or to seek to a frame number/time ?

**Comment by soliton4** [comment]
im araid not
yet ....
