### ISSUE TITLE
Building with multithreaded (emscripten webworker support)

### ISSUE THREAD

**Issue by AlScott006** [mbebenita/Broadway#149]
Hi,

I'm trying to enable pthread support through emscripten however I'm having issues when running the transpiled JS. seems that it's having trouble when trying to open the current document to pass that javascript file to a worker. Could this be an issue with the pre-js code template?

undefined : document.currentScript.src is null 

Has there been any work or an attempt at supporting a multithreaded enabled build for Broadway? I understand that Broadway itself makes little / no use of multi threading but code we have integrated does.  

Any thoughts on this?

**Comment by soliton4** [comment]
can you give a more detailed description of what you want to run in different threads?
i would also be interested in seeing what you modified so far.

**Comment by AlScott006** [comment]
I have integrated some code that breaks the 264 pipeline and performs extra steps to modify the image in specific ways. This code that I have integrated has multi-threading support. However when enabling multi-threading support from emscripten it causes an error very early on in the decoder.js. This code when built standalone through emscripten properly supports and runs in a multithreaded mode. 

I'm trying to debug why when enabling pthreads it seems to have issues here 
`
var currentScriptUrl = ENVIRONMENT_IS_WORKER ? undefined : document.currentScript.src;`

This happens after we call    

```
 var Module = getModule.apply(fakeWindow, [function () {
    }, onPicFun]); Line:119 on DecoderPost.js.
```

This then tries to get the Module but fails on 
```

if (!ENVIRONMENT_IS_PTHREAD) PthreadWorkerInit = {};
var currentScriptUrl = ENVIRONMENT_IS_WORKER ? undefined : document.currentScript.src;
```

currentScript.src (which should be set to <pathto>decoder.js) is null. 

I'm trying to get some insight into why the the javascript document appears to have fallen out of scope / finished being processed when threading is enabled at this point. 

Thanks for the speedy response.

**Comment by soliton4** [comment]
i dont think i can help you much without looking at the code you are compiling.
make a github repository so i can reproduce your errors.
maybe i will be able to help you

**Comment by AlScott006** [comment]
You can reproduce the issue by building Broadway (with no modifications) by adding

`'-s', 'USE_PTHREADS=1'` 

in the make.py.

**Comment by soliton4** [comment]
i dont get the point of using threads in the first place.
the decoder doesnt support multi threaded decoding at this point. unless you can show me code modifications that support threading i see no reason to keep this ticket open
