### ISSUE TITLE
Can‘t decode raw h.264 frame  more than 8100 bytes

### ISSUE THREAD

**Issue by zhiyul** [mbebenita/Broadway#151]
I got raw h.264 frame from an Android device, and I called `player.decode(data)` it works fine. But when I got a  frame that it's `byteLength` is for example `8176`, the `onPictureDecoded` doesn't called.

**Comment by soliton4** [comment]
are you sure its annex b stream? 
i am know the decoder c code a bit and i dont believe there is anything depending on the length of the nal unit.
it is more likely you dont provide a complete nal unit or the stream is encoded with b frames

**Comment by zhiyul** [comment]
Thanks for your reply. I checked the entire transport process again and it seems that Android client lost some frames during transmission. Finally it worked fine.
Thanks again for this great project! 👍
