### ISSUE TITLE
How to debug the decoding?

### ISSUE THREAD

**Issue by omerjerk** [mbebenita/Broadway#154]
Hi,

I've been using BroadwayJS to stream video from Android to the web browser. It was all working fine until recently I made some changes in the Android side and the decoding/rendering in the browser just stopped working.
I'm not able to figure out the issue yet. Everything looks good to me.

Is there anything I can do to debug this on the broadway side?

**Comment by omerjerk** [comment]
Closing this as I found the issue in my Android code. Still, it'd be good if broadway starts spitting some debug logs in the console.

**Comment by soliton4** [comment]
hi, if you really want to debug the broadway code the best is to compile the c sources with your ide / debugger of choice. debugging asm.js code is rather difficult.
console logs could be added, can you open a seperate issue for that?
