### ISSUE TITLE
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by ckproduct** [mbebenita/Broadway#157]
when I feed uint8array to player's decode
It happened like that
![2017-08-08_144227](https://user-images.githubusercontent.com/26317185/29059430-194ffcd8-7c48-11e7-82ef-99a8a2842fd6.png)

canvas have new size (not default size), but still black.

I found some strange in Player.js

> canvasObj.webGLCanvas.drawNextOutputPicture({
>         yData: options.data.subarray(0, ylen),
>         uData: options.data.subarray(ylen, ylen + uvlen),
>         vData: options.data.subarray(ylen + uvlen, ylen + uvlen + uvlen)
>       });

but In YUVCanvas.js 
webGLCanvas.drawNextOutputPicture is like this

> YUVCanvas.prototype.drawNextOutputPicture = function(width, height, croppingParams, data) {
>     var gl = this.contextGL;
>     if(gl) {
>         this.drawNextOuptutPictureGL(width, height, croppingParams, data);
>     } else {
>         this.drawNextOuptutPictureRGBA(width, height, croppingParams, data);
>     }
> };

How to fix them? 
I trying put width and height and data like this

> canvasObj.webGLCanvas.drawNextOutputPicture(width,height,{
>         yData: options.data.subarray(0, ylen),
>         uData: options.data.subarray(ylen, ylen + uvlen),
>         vData: options.data.subarray(ylen + uvlen, ylen + uvlen + uvlen)
>       },options.data);

Now it display 4 same grayscale video side by side....

**Comment by Serveurperso** [comment]
Same problem here

**Comment by soliton4** [comment]
have a look at drawNextOuptutPictureGL
you will see that it expects an object like the one that player.js provides
the signature of the function changed and the drawNextOutputPicture is simply passing through to the configured function.
its not very beautiful and should be changed but is is basically in working order

**Comment by soliton4** [comment]
i assume this is resolved @Serveurperso @ckproduct
