### ISSUE TITLE
broadway html cannot play the video that encoded by ffmpeg

### ISSUE THREAD

**Issue by baozeyanggithub** [mbebenita/Broadway#158]
I use the order which is ffmpeg -y -i /dev/video0 -r 30000/1001 -b:a 2M -bt 4M -vcodec libx264 -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -an targetFile.mp4 ,and then use storyDemo.html to play targetFile.mp4, and the result is the html cannot play the video. so i want to ask for some suggestion,please help me. thank you very mush .

**Comment by soliton4** [comment]
try passing 

-profile:v baseline 

as well

**Comment by baozeyanggithub** [comment]
can you write the detailed commend? I use  ./ffmpeg -i /dev/video0 -r 30000/1001 -vcodec libx264 -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -an output.mp4 -profile:v baseline, but  storyDemo.html cannot play mp4 file, the ffmpeg i use is ffmpeg-3.3.3.
thank you very much!

**Comment by soliton4** [comment]
https://github.com/soliton4/BroadwayStream
uses ffmpeg to encode any sort of video for broadway.
you can copy the command fromt here
