### ISSUE TITLE
If the video format is MPEG-4 visual ,this will not work

### ISSUE THREAD

**Issue by pobc** [mbebenita/Broadway#159]
My video format is MPEG-4 visual, if I decoder this video ,will get error:
Uncaught TypeError: Cannot read property 'avcC' of undefined
    at constructor.play (mp4.js:862)
    at constructor.<anonymous> (mp4.js:848)
    at XMLHttpRequest.xhr.onreadystatechange (stream.js:21)

https://www.dropbox.com/s/git4z42ngv79esf/fff.mp4?dl=0
It's my video.

**Comment by soliton4** [comment]
please refer to the codec limitations mentioned on the readme
