### ISSUE TITLE
Demos gone

### ISSUE THREAD

**Issue by contra** [mbebenita/Broadway#16]
The demo pages give a 404

**Comment by soliton4** [comment]
any reason to keep this issue open?

**Comment by bkw** [comment]
Since you have push rights now, maybe we could try to resurrect the gh-pages of the original repo?
I do not always have the time to keep up, like right now with the fast worker implementation.

**Comment by soliton4** [comment]
exactly - i was just writing the same in the other issue thread
can you pls pr your changes. i will do the updating

**Comment by soliton4** [comment]
@bkw @mbebenita so the demos are now only hosted on @bkw s system? i noticed there are some links in the interwebz pointing to @mbebenita s system.

any chance those will be up and running again?

**Comment by mbebenita** [comment]
To be honest, I have no idea why the demos stopped working on the main repo. I think there was a glitch with github at some point. Would be nice to resurrect them.

**Comment by soliton4** [comment]
hey @mbebenita nice to hear from you ;D

how am i doing so far?

**Comment by soliton4** [comment]
@mbebenita @bkw 
yay!
http://mbebenita.github.io/Broadway/storyDemo.html works again
thanks to @bkw s pr

**Comment by mbebenita** [comment]
> how am i doing so far?

Terrific!

**Comment by soliton4** [comment]
i just finished updating the demos
there are 2 main thread videos and 4 worker videos
2 with webgl fallback solution and 2 with webgl autodetection.

but due to 
https://twitter.com/githubstatus/status/582231080205475841

you cant see it ;(

**Comment by soliton4** [comment]
there it is
http://mbebenita.github.io/Broadway/foxDemo.html

check out the webgl = false mode on chrome ;D

**Comment by mbebenita** [comment]
For me on OSX/Chrome:

main thread - webgl: true fps: 117.18 avg: 101.47
main thread - webgl: false fps: 69.86 avg: 60.32

worker thread - webgl: true fps: 245.32 avg: 221.10
worker thread - webgl: false fps: 123.63 avg: 133.65


The worker / webgl version is ridiculously fast!

**Comment by soliton4** [comment]
what kind of machine do you have?
i have a year old i7 and use linux
i get 183fps avg with webgl + worker

what i wanted to show you is the color errors in chrome in non webgl mode
i opened a bugreport for it and it will be fixed in one of the next releases soon

**Comment by mbebenita** [comment]
I have an 2.8 GHz Intel Core i7 MBP running OSX 10.10.2

**Comment by soliton4** [comment]
this is from the very same sourcecode that is now doing the webgl fallback
https://code.google.com/p/chromium/issues/detail?id=468162

its especially visible at the fox demo
http://mbebenita.github.io/Broadway/foxDemo.html

but also the other demos have slight color errors
my remote desktop looks very psychedelic

**Comment by mbebenita** [comment]
@soliton4 any idea what could be causing the asm.js validation errors? https://twitter.com/kripken/status/582304553778823168

**Comment by soliton4** [comment]
@bkw since the demos work here again i updated the readme to link to @mbebenita s demo page.

thank you for hosting them in the past. 

you seem to be fit with configuring github pages. you are very welcome to contribute the the demo pages in the future.
