### ISSUE TITLE
JCodec's P-Frames not decoding

### ISSUE THREAD

**Issue by simon1492** [mbebenita/Broadway#160]
Hi all,

I'm trying to use Broadway.js to decode a raw h264 stream encoded using [JCodec](http://jcodec.org). As long as i do only encode IDR frames, everything works fine (Great work, thanks a lot!). But once I start encoding P frames, those are silently droped by broadway and only the IDR frames do cause a call to onPictureDecoded.

I created an example h264 file (attached, zip'ed) and ("based on" @amitv87 's answer to issue #115) a basic setup showing the issue:

```
<html>
<body onload="load();">
  
  <script type="text/javascript" src="Decoder.js"></script>
  <script type="text/javascript" src="Player.js"></script>
  
  <script type="text/javascript" src="stream.js"></script>
  
  <script type="text/javascript">
	function H264Player(){
	  console.log('using', this);
	  var p = new Player({
		useWorker: true,
		webgl: false,
		workerFile: "Decoder.js",
	  });

	  document.body.appendChild(p.canvas);
	  var parser = new nalParser(p);
	  this.play = function(buffer){
		parser.parse(buffer);
	  };
	}

	function sleep(millis)
	{
		var date = new Date();
		var curDate = null;
		do { curDate = new Date(); }
		while(curDate-date < millis);
	}

	function nalParser(player){
	  var bufferAr = [];
	  var concatUint8 = function(parAr) {
		if (!parAr || !parAr.length){
		  return new Uint8Array(0);
		};

		if (parAr.length === 1){
		  return parAr[0];
		};

		var completeLength = 0;
		var i = 0;
		var l = parAr.length;
		for (i; i < l; ++i){
		  completeLength += parAr[i].byteLength;
		};

		var res = new Uint8Array(completeLength);
		var filledLength = 0;

		for (i = 0; i < l; ++i){
		  res.set(new Uint8Array(parAr[i]), filledLength);
		  filledLength += parAr[i].byteLength;
		};
		return res;
	  };
	  this.parse = function(buffer){
		if (!(buffer && buffer.byteLength)){
		  return;
		};
		var data = new Uint8Array(buffer);
		var hit = function(subarray){
		  if (subarray){
			bufferAr.push(subarray);
		  };
		  var buff = concatUint8(bufferAr);
		  player.decode(buff);
		  bufferAr = [];
		};

		var b = 0;
		var lastStart = 0;

		var l = data.length;
		var zeroCnt = 0;

		for (b = 0; b < l; ++b){
		  if (data[b] === 0){
			zeroCnt++;
		  }else{
			if (data[b] == 1){
			  if (zeroCnt >= 3){
				if (lastStart < b - 3){
				  hit(data.subarray(lastStart, b - 3));
				  lastStart = b - 3;
				}else if (bufferAr.length){
				  hit();
				}
			  };
			};
			zeroCnt = 0;
		  };
		};
		if (lastStart < data.length){
		  bufferAr.push(data.subarray(lastStart));
		};
	  };
	}
  
  
    function load() {
	
      var stream = new Stream('test-15fps.h264');
	  var pl = new H264Player();

	  stream.readAll(
		function(){},
		function(buf) {pl.play(buf);});
    }
  </script>
  </body>
</html>
```

Any suggestions how i could get it to work?

Thanks alot and kind regards,
Simon
[test-15fps.zip](https://github.com/mbebenita/Broadway/files/1358207/test-15fps.zip)

**Comment by soliton4** [comment]
hi
i dont have the time to investigate this thuroly atm but i am willing to point you in the right direction and assist in your investigation

do you have the means to compile and debug the c sources of the decoder?

if so please do and feed them with your stream

set a breakpoint here and check if the p-frame triggers this code:
https://github.com/mbebenita/Broadway/blob/d28fd6328a299e1bfc8a883bf2b94b7e53a2b77e/Decoder/src/h264bsd_decoder.c#L491

let me know your outcome and ill continue to help you

**Comment by simon1492** [comment]
Hi,

many thanks for your willingness to help. I do not currently have a setuip to compile and try it and also little time to investigate. I'll try do find the time and let you know!

Regards,
Simon

**Comment by simon1492** [comment]
Hi, is it possible to enable the libstageflight debug output in broadway?
Thanks & regards,
Simon

**Comment by soliton4** [comment]
broadway is in its intended usecase a javascript project.
the c sources can be used in a c / c++ project but thats not the goal of this project.

i only mentioned it to allow you investigate what the problem with your stream might be.

**Comment by simon1492** [comment]
Thanks, the error has meanwhile been adressed and fixed in the encoder jcodec.

Thanks for theresponse,
Regatds, Simon


Am 20. Februar 2018 10:14:30 nachm. schrieb soliton4 
<notifications@github.com>:
