### ISSUE TITLE
P frames encoded using libx264 do not decode correctly

### ISSUE THREAD

**Issue by annazhelt** [mbebenita/Broadway#161]
Hello, 

I am encoding video frames in C++ using libavcodec-dev installed on ubunutu 14.04. The codec library itself is libx264 which comes as part of libavcodec-dev. I have set profile to baseline, tune to fastdecode, and set  AVCodecContext options weightp to 0, coder_type to 0, max_b_frames to 0.

It works great when I set group of picture size to 1 i.e. only send I frames. When I increase the group of picture size and start sending P frames as well, the P frames do not decode properly. They do trigger the decoding callback. `onPicFun` is called for every second p frame. However, the buffer that is passed in to onPicFun is the same for every successive P frame until a new I frame is passed in. The video picture only changes on every I frame. 

I split up my input buffer into NAL units. I have tried both taking off the 00 00 01 and keeping it. It does not make a difference. The sequence of frames that I pass in is SPS, PPS, I , and then 24 P frames. Then repeat.

I have confirmed that the successive encoded P frames do not match. I am also able to play my encoded video using gstreamer. (I send the encoded packets to a UDP socket which gstreamer listens to. The video plays well). 

Has anyone seen a similar issue? 

Thank you very much for your help!

**Comment by soliton4** [comment]
hi and thx for the detailed report.

i know for sure that broadway is compatible with x264 encoded data streams.

what looks odd to me is you describe the seperator as 00 00 01
it should be 00 00 00 01 and as far as i remember you keep it in when submitting the nal unit
it should not matter if the sps and pps are in their own nal unit or not, but just to make sure can you describe if you have one first nal unit, containing subunits of sps, pps and i frame that are seperated via 00 00 01 and the nal unit itself starting with 00 00 00 01
all following nal units should be one frame starting with 00 00 00 01

**Comment by annazhelt** [comment]
I pass in my raw frames for encoding to `encode_video2` in libavcodec. `encode_video2` populates an AVPacket with the encoded frame. I send a buffer containing the data from each packet over a websocket to my front-end application. 

The first buffer I receive is
00 00 00 01 (SPS frame data) 00 00 00 01 (PPS frame data) 00 00 01 (I frame data)
The next 24 buffers I receive are 
00 00 00 01 (P frame data)

I have read that the start prefix can be either 00 00 01 or 00 00 00 01 and depends on the encoder. I have also read that 00 00 00 01 usually prefixes the first frame in a stream or SPS and PPS frames, while 00 00 01 prefixes the subsequent frames. However, I cannot find that stackoverflow post anymore.

**Comment by soliton4** [comment]
yeah you are right that the prefixes can vary.
however from what i have seen the most common is to sepearate real packets with 00 00 00 01 and to use 00 00 01 within the packets to be sorted out by the decoder

the way you describe your stream is slightly weird. and how i have seen it before

can you try the following:
copy the data from the first buffer into 3 seperate buffers
1st: 00 00 00 01 SPS
2nd: 00 00 00 01 PPS
3rd: 00 00 00 01 (i frame data)

note that you have to insert an extra 00 for the 3rd buffer

pass them all into the decode function and see if that makes a difference

the p frame data looks good from what i can tell. make sure to allways call the function with complete nal units and not with parts of the actual nal unit

**Comment by annazhelt** [comment]
I tried the suggestion. Unfortunately, I am still getting the same result.

**Comment by soliton4** [comment]
i could take a look at your stream i suppose. if you post it here or in your github. first 25 frames should be sufficient. but i wont be able to for a while.

alternatively you can try debug it yourself. do you have access to a c debugger? then you can run the sources in this repo

**Comment by annazhelt** [comment]
I do have access to a C debugger. How would I go about running the sources in this repo? Is there a makefile?

I was thinking maybe I am not setting the correct encoder options. I have:
```
codec_context_->bit_rate = H264_ENCODER_BITRATE;
codec_context_->width = width;
codec_context_->height = height;
codec_context_->time_base = (AVRational){1,37};
codec_context_->gop_size = H264_ENCODER_GOP_LENGTH;
codec_context_->max_b_frames = 0;
codec_context_->pix_fmt = AV_PIX_FMT_YUV420P;
codec_context_->coder_type = 0;
av_opt_set_int(codec_context_, "weightp",0 ,1);
av_opt_set(codec_context_, "tune", "fastdecode", 1);
av_opt_set(codec_context_, "profile", "baseline",1);
```
The fastdecode tune option is supposed to turn of the loop filter in libx264. I have tired using av_opt_set both on codec_context_ and codec_context_->priv_data. Doesn't make a difference. Do those look correct?

**Comment by soliton4** [comment]
have you tried this: https://github.com/soliton4/BroadwayStream

the c sources are quite straight forward but you have make your own projecet with whatever dev environment you prefer

this is a good place to get started:
https://github.com/mbebenita/Broadway/blob/master/Decoder/src/Decoder.c#L67
the interface is a little awkward because its meant to link to a js based api but you should be able to get it.

**Comment by annazhelt** [comment]
ok, thank you very much for your help. I'll try it.

**Comment by goosui** [comment]
Hello,

I get date use ajax. I can't decode P frame too.

Has anyone seen a similar issue?

Thank you very much for your help!


===================================================================
code:
===================================================================<!doctype html>
<html>
<head>
  <script type="text/javascript" src="Decoder.js"></script>
  <script type="text/javascript" src="YUVCanvas.js"></script>
  <script type="text/javascript" src="Player.js"></script>
</head>
<body>
<canvas id="canvasId" width="640" height="480"></canvas>
<div id="rgbId">
</div>

<button id="closeSendId">
<script>
	//第一种方式
	var canvas = document.getElementById('canvasId');
	canvas.width = 1280;
	canvas.height =720;
	canvas.style.zIndex = 8;
	canvas.style.position = "absolute";	
	var ctx2D = canvas.getContext('2d');

	var img = document.createElement("img");
    img.onload = function(e) {
		ctx2D.drawImage(this,0,0,1280,720);
		console.log("---------draw");
        window.URL.revokeObjectURL(this.src); 
    };
	
	var pDecoder = new Decoder({
	  rgb:true,
	});
	var k=1;
	pDecoder.onPictureDecoded =  function(buffer, width, height, infos){
		//if(k==1){
		//k=2;
		//var blob = new Blob([buffer.buffer]);       // 注意必须包裹[]
		//img.src = window.URL.createObjectURL(blob);
		 
		console.log("------66---width="+width);
		console.log("------77--height="+height);
		var imageData = ctx2D.getImageData(0, 0, width, height);
		imageData.data.set(buffer);
        ctx2D.putImageData(imageData, 0, 0);
		
		//ctx2D.fillStyle=buffer;
		//ctx2D.fillRect(0,0,640,480); 
		
		//document.getElementById('rgbId').innerHTML = buffer;
		//console.log("------55---buffer[0]="+buffer[0]);
		//console.log("------55---length="+buffer.length);
		//ctx2D.drawImage(buffer,0,0,width,height);
		//console.log("------66---width="+width);
		console.log("------77--width="+height);
		//}
		//GetImage();
	};
	//pDecoder.decode(<h264 data>);

	

	var xhr = new XMLHttpRequest(); 
	function GetImage(){
		var timestamp = (new Date()).valueOf();
		xhr.open('GET', 'http://192.168.1.152/enc0.h264?t='+timestamp, true); 
		xhr.send();
	}
	xhr.type="HEAD";	
	xhr.responseType = 'arraybuffer'; 
	xhr.onload = function(e) {  
		if (this.status == 200) {
			var uInt8 = new Uint8Array(this.response);		
			if(uInt8[0]==0){
				console.log('---------丢掉 uInt8[0]='+uInt8[0]);	
				return;
			}
			console.log('--------1-uInt8[0]='+uInt8[0]);
			if(uInt8[0]==85){
				uInt8[0] = 0;		
				//var copyU8 = new Uint8Array(uInt8.length);
				//copyU8.set(uInt8);

				var  naltype;
			  if (uInt8[4] == 0x65) {
				naltype = "I frame";	
			  }
			  else if (uInt8[4] == 0x61) {
				naltype = "P frame";
				pDecoder.decode(uInt8);
			  }
			  else if (uInt8[4] == 0x67) {
				naltype = "SPS";
				pDecoder.decode(uInt8);
			  }
			  else if (uInt8[4] == 0x68) {
				naltype = "PPS";
				
			  }			
			  
				
			}
			//console.log('---------end');	
			//p.decode(uInt8);
			//console.log('---------p.webgl='+p.webgl);	
			//var buffer = uInt8.buffer;
			//var blob = new Blob([buffer]);       // 注意必须包裹[]	
			//img.src = window.URL.createObjectURL(blob);
		}
	}; 
	function getBinDate(){
		 var copyU8 = new Uint8Array(32); 
		 ws.send(copyU8);
	}

	//setInterval("getBinDate()",40);
	setInterval("GetImage()",50);
	//setTimeout("getBinDate()",50);

	

</script>
</body>
</html>

**Comment by annazhelt** [comment]
Hi, yes, i actually just recently solved it. There was a bug in my code. When sending pframe data over a websocket from my server, I was not passing in the correct size argument. The decoder works great. Thank you! 

I can see that in your onload function you only pass in certain frame types for decoding. To decode p frames you need to pass in all the previous frames to the decoder as well. P frames depend on the previous I frame for decoding.

**Comment by soliton4** [comment]
you make it sound like you create a new decoder for every single frame @annazhelt

**Comment by goosui** [comment]
@annazhelt 
How do you decode P frames in your program?

**Comment by goosui** [comment]
are you one frame one frame to send frame websocket？

**Comment by goosui** [comment]
Can decode p frame from net？

your demos is to decode one file.

thank you @soliton4

**Comment by annazhelt** [comment]
@soliton4 I do not think I create a new decoder for every frame. I instantiate a new player once. Then call `this.player.decode(new Uint8Array(e.data))` whenever I receive a message on my websocket. On the backend, I was instantiating the vector that contained the frame data to send with the wrong size. So, I'm guessing I was sending garbage data after the end of my frame which prevented it from being decoded. 

@goosui I'll reply in more detail under the issue that you created.

**Comment by goosui** [comment]
@annazhelt thank you
