### ISSUE TITLE
Decoding issues

### ISSUE THREAD

**Issue by luismcosta** [mbebenita/Broadway#165]
Hi,

I'm experimenting with Broadway and got it to work.
My use case:
The video stream captured by the captured and h264 encoded. Then the encoded frames are sent, via WS, to the browser.
It works relatively well. However, I see a lot of squares (aka compression artifacts), when the camera captures movement.
I'm encoding with a gop of 10 and zero b-frames. I'm capturing 20fps.
I'm able to see the frames being correctly decoded using a ffmpeg-based component that I have - I see the video without any glitches.

I wonder if frames are being dropped or being decoded out-of-order.

I could fin any debugging information.
Are there any troubleshooting aids? Can someone share some thoughts on why is this happening?

Thanks,
 Luís

**Comment by soliton4** [comment]
you wrote you could fin any debugging information.
what do you mean?

have you tried a higher target bitrate?

if you decode complete nal units in order there should be no frame dropping. post a screenshot of what you see so i can tell more.

**Comment by luismcosta** [comment]
Hi @soliton4 !

Thanks for the quick reply. I didn't answer immediately because working in something else.

Regarding the issue.

What I meant by "I could find any debugging information." was if there is any option that can be activated so the that the Decoder could log some errors like "error processing frame" and such. Meanwhile I've looked at the source code and I don't think there is.

It was not necessary to use a higher frame rate. 5fps works fine.

**There are no Compression Artifacts. The library is working as expected.** I was send more data in the stream than the actual frame.
So, I'm closing the issue.

Thanks!
