### ISSUE TITLE
does not work with latest emscripten

### ISSUE THREAD

**Issue by bkw** [mbebenita/Broadway#17]
There have been quite some changes to emscripten lately, a good summary can found here: http://mozakai.blogspot.de/2012/11/emscripten-compiler-upgrades.html

I could not get the current master of emscripten to build a working Broadway.js without disabling every optimization: closure-compiler breaks the modules patching, and even -O1 only results in a grey canvas (no error messages in the console).

Has anybody gotten this to work already? I'd love to put those the new optimizations to work.

**Comment by saste** [comment]
The problem was probably due to this:
https://github.com/kripken/emscripten/issues/3082

I was able to compile and use code compiled with latest emscripten.

See also:
https://github.com/mbebenita/Broadway/pull/42

**Comment by soliton4** [comment]
it does now
https://github.com/mbebenita/Broadway/commit/736e9230f86baae6bdcd98c286aad9cf78e9965b

emscripten 1.29.0
