### ISSUE TITLE
Any way to "warm up" the webworker decoder?

### ISSUE THREAD

**Issue by scaret** [mbebenita/Broadway#171]
Im using Broadway decoder in worker mode. The H264 stream is in periodic keyframe（like SPS->PPS->I->P->P->P->SPS->PPS->I->P->P->P）。

I found that on desktop chrome, the decoder will spend about 200ms for the first I frame, but will spend only 20ms on the second I frame. On low-hardware Android, it takes about 2 second for the first I frame but about 200ms for the second.

So it seems that the webworker decoder still need some warmup after it is initialized. my workaround solution is to let the player decode 3 frames before I receive any frame. And it works!

What causes the situation, and is there better solution?

**Comment by soliton4** [comment]
that is probably some chrome optimization / initialization
you could let it decode a dummy frame. like your workarround to have it in an optimized state

**Comment by soliton4** [comment]
huge is relative. i think its somewhere in the order of 20-40 mb
