### ISSUE TITLE
Rendering glitch on certain rows and columns in decoded image

### ISSUE THREAD

**Issue by OllieJones** [mbebenita/Broadway#174]
I'm using Broadway to render H264 images generated from screen captures.   (It's great stuff, thanks!)

I've found a rendering glitch that's made obvious when the screen contents are text.

Example:
![image](https://user-images.githubusercontent.com/9804013/41069827-93bdd144-69bd-11e8-88b8-224c755b4abb.png)

On the left is an image rendered by Broadway. On the right is an image rendered by a media player from the same data stream.

Take a look at two things to see what I mean. 
1. There's a problem with the way Broadway rendered the bottom of the letters in "California and New Jersey." They seem to be stretched vertically, slightly.
2. There's a problem with the letter "r" in "contend fo**r** at least" It looks like it's stretched horizontally.

These glitches come up at constant offsets from the top left of the rendered image.

Does Broadway render tile-by-tile? If so, is it possible there's a glitch at the edges of tiles? Is there any way to correct this problem?

**Comment by soliton4** [comment]
i am looking at the post through a remote desktop using broadway as renderer. the problem you describe is most likely with your local canvas. it seems to be zoomed a bit or given a hight different than what the player.js sets it to.
if you manually set your hight notice that h264 streams allways need a hight dividable by 2. in broadway you also need a width dividable by 16. if your stream has a different width / height, broadway will compensate by providing a larger output.
i hope that helped

**Comment by OllieJones** [comment]
@soliton4  Thanks for your reply.

I don't believe canvas scaling is my problem. I have done some work to isolate it.  I have also eliminated canvas scaling as a problem by making sure the canvas size is precisely the same as the video size.  I am willing to try to fix this, but if you can point me to the right bit of code it will help me.

 I'm using a test pattern containing black diagonal lines and some red and green index lines. I believe YUVWebGLCanvas.js actually has an off-by-one error as it positions blocks of output data on the canvas. 

Here is a zip file containing a fragmented mp4 file demonstrating the problem.  
[blocky-test-pattern368x656.zip](https://github.com/mbebenita/Broadway/files/2090080/blocky-test-pattern368x656.zip)  When I play this file with BroadwayPlayer it shows the glitches. When I play it with the mp4 player in Google Chrome or Firefox or the Quicktime Player or the Windows Media Player, it does not show the glitches. That's why I think it's an issue in YUVWebGLCanvas. The sample mp4 file is very short, and shows just enough movement to show that the glitch remains in the same place on the decoded image as the source image moves. (The source image contains a screengrab from an iOS device.)

Here's an explanation  of the glitch.
![glitch1](https://user-images.githubusercontent.com/9804013/41234110-4aaec4be-6d59-11e8-84dd-bea81f10315d.png)

This is a screenshot of the decoded image rendered by YUVWebGLCanvas. The items circled in blue show both vertical glitches and horizontal glitches.

![glitch2](https://user-images.githubusercontent.com/9804013/41234336-e0eb58c0-6d59-11e8-8d9a-4c5b179d1449.png)

This is a portion of that same image blown up.

I *think* this is what happens. Suppose the decoded image should be

+----------------+
|AAAABBBBCCCCDDDD|
|AAAABBBBCCCCDDDD|
|AAAABBBBCCCCDDDD|
|AAAABBBBCCCCDDDD|
|EEEEFFFFGGGGHHHH|
|EEEEFFFFGGGGHHHH|
|EEEEFFFFGGGGHHHH|
|EEEEFFFFGGGGHHHH|
+----------------+

I think YUVWebGLCanvas renders it this way and then scales the canvas to the decoded size.

+-------------------+
|AAAAABBBBBCCCCCDDDD|
|AAAAABBBBBCCCCCDDDD|
|AAAAABBBBBCCCCCDDDD|
|AAAAABBBBBCCCCCDDDD|
|AAAAABBBBBCCCCCDDDD|
|EEEEEFFFFFGGGGGHHHH|
|EEEEEFFFFFGGGGGHHHH|
|EEEEEFFFFFGGGGGHHHH|
|EEEEEFFFFFGGGGGHHHH|
|EEEEEFFFFFGGGGGHHHH|
+-------------------+

Again, I'm happy to try to fix this if you can point me in the right direction, or work around it.

Best regards,
Oliver Jones

**Comment by OllieJones** [comment]
Further troubleshooting:  disabling webGL (`webgl: false`) makes the rendering glitch go away.

(Sorry, for the slow followup I've been off doing other things.)

**Comment by soliton4** [comment]
please provide a small git repository that makes it easy for me to reproduce your error on a chromium based browser

**Comment by OllieJones** [comment]
Oh, facepalm!

I was using the Broadway client code referenced in the BroadwayStream submodule link. It was an old commit of Broadway. Moving up to the latest Broadway build resolved the problem.  All is well. I'll do a pr to move BroadwayStream's submodule link forward.

Thanks for your help.
