### ISSUE TITLE
Streaming decoder is very slow on Mobile

### ISSUE THREAD

**Issue by Esser420** [mbebenita/Broadway#176]
I'm working on a streaming application with raspberry pi and used visio (https://github.com/Dregu/visio) which in turn uses this project to decode h264 streams on the fly.

I've managed to get it to work very well on my Desktop browser. But on mobile devices (iPhone, iPad) it is incredibly slow! Less tahn 1 fps where I can get 28fps flawlessly on my Desktop.

Does this have anything to do with the decoder?

The visio project has a small debugger thing which shows that the decoder is receiving lots of NAL frames but only producing less than 1% in actual frames.

Any insight on what the issue might be?

**Comment by Esser420** [comment]
I did some further tests. I have this issue on all mobile web browsers (safari, firefox, chrome). On desktop I have the same issue with safari, but firefox and chrome work fine.

Any thoughts why this happens and is it possible to tweak some settings to make it work with these browsers?

**Comment by soliton4** [comment]
i have gotten broadway to perform pretty well on android
you browser must support asm.js
you can play with the settings of emscripten and compile broadway yourself.
let me know if that makes a difference for you please

**Comment by OllieJones** [comment]
I've gotten to work well on Android, iOS, and Chromebooks, without any notable performance problems.

(Note that most frames are encoded with multiple NALUs. Also note that you can pass NALUs one by one to `decode()` without prefixing them with 0,0,1 separators. It's always good to avoid copying data if possible.)

**Comment by Jessica-Mao** [comment]
I have also the same issue, and today I use emscripten to compile Decoder.c, but the Decoder.js can't be used. I want to know which file must be re-compile, thanks.

**Comment by Esser420** [comment]
I've been using this project: https://github.com/Dregu/visio

Then I use PiCamera library to send individual NAL frames over a WebSocket.

Strangely enough it started working on Safari on MacBook. Still no luck on mobile browsers though..

What can I do to debug this? My guess it's not using WebGL (but I'm not very knowledgeable on this topic)

**Comment by Esser420** [comment]
Ok basically after learning some javascript and more about browser compatibility and asm.js I found this unfortunately: https://caniuse.com/#feat=asmjs

Which basically explains the low performance on IOS and MacOS Safari, asm.js is just not compiled AOT.

Closing the issue because of this.
