### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by fxfactorial** [mbebenita/Broadway#177]
using 0.0.2 in a create-react-app project

and getting this error 
```
Decoder.js:58 Uncaught ReferenceError: global is not defined
    at Object.getModule (Decoder.js:58)
    at new Decoder (Decoder.js:169)
    at Decoder.js:733
```

in this kind of code sample:

```javascript
import H264Player from 'broadwayjs/Player/Player';

    this.player = new H264Player({
      useWorker: true,
      // reuseMemory: true,
      webgl: 'auto',
      workerFile: '/Decoder.js'
    });
```

where `/Decoder.js` is located in my `public/Decoder.js` so I assume it means the broadway will do its own query for this Decoder.js file. 

So I am not clear why global would not be defined in the worker thread

**Comment by soliton4** [comment]
make sure you use the latest version
workerfile is simple the url from which the workter thread is initialized

**Comment by fxfactorial** [comment]
@soliton4 sorry, I don't quite understand. 

I did `cp node_modules/broadway/Decoder.js public`

Can you show me a code sample of what you mean?

**Comment by fxfactorial** [comment]
Okay so I could just copy your Decoder.js and my current step would work ?
