### ISSUE TITLE
Clipped display, responsive display: how to implement?

### ISSUE THREAD

**Issue by OllieJones** [mbebenita/Broadway#180]
I am playing both webm and fmp4 streams, deboxing the NALUs and passing them to Player.decode(). It all works amazingly well.  Thanks for Broadway!

I'm looking for advice on _clipping_ and on _resizing_ the rendered image, scaling it up or down according to typical responsive-web rendering.  If there's a way to do these things with the existing code, great. If not, I have some time to adapt the code to add these features, and submit a PR.

**Responsive resizing**
My users want their video windows to scale up and down as they resize their browser windows. Is there a way to get YUVCanvas to apply some kind of scale factor to the rendered video? Is there a way to set up Player to respond to instructions to change the scale? 

**Clipping**
I'm getting a stream (webm as it happens) from a webcam, for which the source data is 293x240.  (Sweet: the width is a prime number. Webcams!?!) The H.264 stream, rounded up to the nearest macroblock, is 304x240, as predicted. This data stream contains an ugly 11-pixel-wide black stripe on the right.  In my application, I don't have complete control over the video source, so I'd like to get this right for the viewer of video.

From my deboxing code I retrieve the original source data size (I adapted https://github.com/themasch/node-ebml to debox webm). 

Do you have any suggestions about how to clip the rendered image to the source video size, to eliminate the black bar? Is it possible to give the Player or the YUVCanvas object a clipped size?

Similarly, my application will benefit

**Comment by OllieJones** [comment]
I've implemented what I need and submitted this pull request. https://github.com/mbebenita/Broadway/pull/184

**Comment by Tauka** [comment]
Hi, why not just apply `width: 100%, height: 100%` styles to the canvas? Then the browser will handle resizing as you resize the window

**Comment by soliton4** [comment]
@Tauka  as it is the code auto detects the availability of webgl. the opengl rendering might actually work that way - need confirmation.
but the non webgl code will most likely not work. you have to adjust the zooming in the actual render routine
