### ISSUE TITLE
1920*1080 -25fps，the I  frame decode use  webgl delay

### ISSUE THREAD

**Issue by xuruncheng** [mbebenita/Broadway#186]

**Comment by xuruncheng** [comment]
I have use the broadway in 1920*1080,  but  every I frame delay obvious，Is there any possibility of optimization. this problem in  low  resolution for example 720p is not obvious。

**Comment by soliton4** [comment]
you could try sticking to p-frames

**Comment by yahsaves** [comment]
What browser/hardware configuration are you running on? 

Also are you letting the program decode the frames as fast as possible, or did you write you own custom frame limiter? I know you said 25fps in your question, but I'm not sure if that's measured performance, or desired performance.

**Comment by xuruncheng** [comment]
@yahsaves   the hardware configuration is auto. I mean is   the 25 fps  is not high. so  the browser may be can decode.  but  in my test  the I frame  decode   picture not well。the  delay time  is  obvious.

**Comment by xuruncheng** [comment]
@soliton4   hello,  your  suggest，  i‘m not  know how to  change the  program  。 can  you   tell me  more。 thankyou  very much。

**Comment by yahsaves** [comment]
@xuruncheng I'm sorry I believe you misunderstood me. I'm not asking if you are using webGL or not (which is what I believe you have set to auto), but rather how fast is the device you are using? 

Also what is 25 fps? Your videos encoded framerate? Or the decode performance? 

The reason I ask is 25 fps is actually pretty reasonable, if it's only the iframes that are slower you can "buffer" the video a few frames before playback. This way when a frame is taking too long to decode you have a few buffer frames ahead of it to help you out. 

This would require some custom code, which I can help you implement, but you'll need to understand basic javascript.

**Comment by xuruncheng** [comment]
@yahsaves  hello,  the "25 fps"   is in the  h264 file  i  send to de websocket  number  and (also is the h264 file code number) .  in  my  test  when i  send one   frame ,i  have   set some  delay(10ms),to allow  browser decode it.  (BTW,  i 'm chinese people, if you have  wechat  or qq  327731196, we can  talk together as well ，thank you！！)

**Comment by yahsaves** [comment]
@xuruncheng  10ms per frame is roughly 100 frames per second of decoding speed. That is blazing fast for a pre-rendered animation. It's even above the 60 fps interactive graphics require. 

Why don't you just put a request animation throttle on the "pic ++" code in mp4.js. This alone should buffer out any performance issues you see with the Iframe. Odds are you are decoding faster than you can display the frames.

**Comment by xuruncheng** [comment]
@yahsaves  the requestanimationframe i have used，but the i frame delay problem is not resolved. i change the progrem  make a js  buffer,to receive  more  frame.but in canvas  picture the  i  frame fresh is also  slow.the  i  frame  length  is  morethan 140000.  i donot how to chang it  better.try  and  try.....

**Comment by xuruncheng** [comment]
@yahsaves  and in the  720p,this  problem is not happen.

**Comment by benjha** [comment]
Hi all,

I have a similar issue but my guess here is my encoder is sending frames faster than Broadway.js can consume. The same story: sending frames through websockets to a web browser client. 

Is there any signal from Player.js indicating the decoding has  finished ?, then I can send a flag to the encoder requesting a new frame.

**Comment by soliton4** [comment]
hi @benjha 
after a picture is decoded the onpicdecoded function is called
you can see it here

https://github.com/mbebenita/Broadway/blob/master/Player/Decoder.js#L165

**Comment by soliton4** [comment]
@benjha  please take the time and read the documentation
there is a mention of this funcion in Decoder.js

**Comment by benjha** [comment]
Thanks,

Sending a flag to the server requesting a new frame inside onPictureDecoded (around lines 103) within Player.js did the work.

**Comment by xuruncheng** [comment]
I have resolve the problem ，it caused by the   frame send  speed 。thanks！
