### ISSUE TITLE
Integrating the broadway-decoder into Blazor for live streaming.

### ISSUE THREAD

**Issue by ChristopherSchoening** [mbebenita/Broadway#192]
Hi,
I'm trying to use the decoder for a live stream in Blazor(https://www.blazor.net) with jsinterop and can't figure out how to to it.

I included the avc.js file into my project but I can't instantiate avc. Blazor's webassembly doesn't seem to get along with the code in avc.js very well.
Any ideas on how to go about this?

I've seen other issues related to live streaming (https://github.com/mbebenita/Broadway/issues/9) and adapted my code to something equivalent to this (as suggested by mbebenita in the linked issue):
```javascript
// avc decoding snippet
var avc = new Avc();
avc.onPictureDecoded = function (buffer, width, height) {
// paint decoded buffer
};
avc.decode(chunkOfStreamedData);
avc.decode(chunkOfStreamedData);

**Comment by soliton4** [comment]
i am not a blazer user and i do not understand the question. 
can you tell us what exactly doesnt work? what is the expected outcome? what is the actual outcome?

**Comment by ChristopherSchoening** [comment]
My main goal is to decode raw h.264 frames which I receive live over a fetch-request and display them in a canvas. I expect that when I create an avc-object and parse the h.264 frames into the `decode`method of it that I would then be able to paint my canvas in the `onPictureDecoded` method (somehow - didn't plan that much ahead).

I included the code from avc.js into my project like this: 
var avc = function(){
        //code from avc.js
}
(I did it this way because I can't deal with multiple files with blazor's interop.)
Is it possible to use avc.js in this way, alone, in a web-application at all?

When I'm trying to create an avc-object `var decoder = new avc();` I get the following messages from blazor's wasm:
![image](https://user-images.githubusercontent.com/32585653/49368871-36656a00-f6f0-11e8-995b-3b37fb92e882.png)
My guess is that blazor's webassembly can't deal with the modules used inside avc.js but I don't know how to do anything about it since I'm new to both javascript and working with webassembly. 

Do I need the avc.wasm file(s) and if so how can I integrate them into my project? Are there flaws in my approach?
Any help would be much appreciated.

**Comment by soliton4** [comment]
```
var avc = function(){
//code from avc.js
}
```
is probably not enough to use broadway. you will have to use the actual files in the Player subfolder or know exactly what you are doing

so blazor is a browser?

**Comment by ChristopherSchoening** [comment]
that's a bummer. I can't use multiple .js files in my project since I'm bound to use blazor's jsinterop which to my knowledge only allows for invoking single methods and doesn't support other js programming structures. (If I'm not mistaken) 

No, quoting from their FAQ (https://blazor.net/docs/introduction/faq.html): 
'What is Blazor?
Blazor is a single-page web app framework built on .NET that runs in the browser with WebAssembly.'

**Comment by soliton4** [comment]
well if your browser supports webassembly it should work. as for blazor, i am not a blazor user nor can i support it

**Comment by ChristopherSchoening** [comment]
Ok, thanks for your help anyways.
