### ISSUE TITLE
I can't read video file

### ISSUE THREAD

**Issue by Tryliom** [mbebenita/Broadway#193]
I've try this code to read my locally h264 file but it display only a black screen on canvas.
```Javascript
      var br = require("broadway-player");
      var player = new br.Player({
        size: {
          width: 555,
          height: 312
        }
      });
      player.canvas;
      document.getElementById("h264Player").appendChild(player.domNode);
      player.decode(test_vid);
```

I don't understand how it works.

What is false in my code, have I forgot something ? Because I don't find any other documentation about that.

**Comment by soliton4** [comment]
please formulate the issue in the form of a specific question that can be answered

**Comment by Tryliom** [comment]
So I have do a single app clean with only this code:
```
import React, { Component } from 'react';
import test_vid from './Record5.h264';

class App extends Component {

  componentDidMount() {
    fetch(test_vid).then(r => r.text()).then(data => {
      var br = require("broadway-player");
      var player = new br.Player({
        size: {
          width: 555,
          height: 312
        }
      });
      player.canvas;
      document.getElementById("App").appendChild(player.domNode);
      player.decode(data);
    });
  }

  render() {
    return (
      <div id="App">
      </div>
    );
  }
}

export default App;
```

And when I execute it I have this:
![screenshot 2018-12-17 at 17 51 00](https://user-images.githubusercontent.com/23244518/50102029-59316b80-0224-11e9-8073-322f823cac0d.png)

So the question was: Why it's crash ? I need documentation about this module.

**Comment by soliton4** [comment]
looks like you are running a modified version of decoder.js
https://github.com/mbebenita/Broadway/blob/master/Player/Decoder.js#L506
