### ISSUE TITLE
Slower performance and screen corruption in mac safari

### ISSUE THREAD

**Issue by Happilyraj** [mbebenita/Broadway#21]
In mac mini safari broadway ,performance is not so  good.I tried demo fps come as ~3-5 fps.On same mac chrome is working as expected(>30 fps for demo).In safari after  decoding certain number of frames screen corruption start to happen and it is consistent.

**Comment by soliton4** [comment]
the code depends on asm.js  
a highly optimized subset of javascript.

it is to my knowledge at this point only implemented in firefox and chrome.
the frontend rendering is depending on webgl, althou i provided a fallback:
https://github.com/mbebenita/Broadway/pull/44

if you browser does not optimize asm.js it will be very very slow

if your machine has issues with opengl or your browser has issues with webgl pixel errors are to be expected.

on the latest chrome version the yuv2rbg transformation doesnt work correctly- resulting in psychedelic pictures

you are on the very forefront of what is possible with javascript. use firefox to be on the safe side.
