### ISSUE TITLE
Can I optimize H.264 decoder module for growing performance of speed.

### ISSUE THREAD

**Issue by Andrey820** [mbebenita/Broadway#210]
I want to grow the performance of decoding speed.

So I'm going to try with build the decoder module with emscriptien.

The issues are as follow:

1. The emscripten version is 1.35.12. But I can't downgrade the version of emscripten.
2. I can't confirm if the decoder module is most optimize.

Please help me.

Thank you

**Comment by soliton4** [comment]
im not sure if i can help you.
what do you need help with in particular?

**Comment by SkeletonKing** [comment]
I'm going to improve the speed of the decoding module.
Please help me.
How can I optimize this module(decoding module).

**Comment by soliton4** [comment]
i am not sure what you are asking me

if you see potential for optimization i am happy to help you with the details.

your question seems incredibly generic

**Comment by beliverwww** [comment]
So, you try to most optimize in your side.

If you try to most optimize in your side, I don't try with my side.

Please let me know.

Thank you.

**Comment by soliton4** [comment]
closing this because its obviously abuse
