### ISSUE TITLE
ffmpeg stream appears glitchy

### ISSUE THREAD

**Issue by DAB0mB** [mbebenita/Broadway#221]
My program is fairly simple: I have a client that records the desktop using ffmpeg, streams it to a server using REST, which then broadcasts the stream to app users. Again, everything is done using REST, no websockets whatsoever, but I suppose it doesn't really matter. Below is a GIF that shows exactly what happens (wait a few seconds for it to load if necessary):

![demo](https://user-images.githubusercontent.com/7648874/92283501-b0033b00-ef08-11ea-81ae-3c0d77f6436a.gif)

This is how I used ffmpeg to stream my desktop:

```js
    const displayArgs = [];
    {
      const { stdout } = await execa('xrandr', this.config);
      const [, w, h] = stdout.split('\n')[0].match(/current +(\d+) *x *(\d+)/i);

      displayArgs.push('-f', 'x11grab', '-r', '30', '-s', `${w}x${h}`, '-i', `${config.display}.0+0,0`);
    }

    const ffmpegProcess = this.execa([
      ...displayArgs,
      '-vcodec', 'libx264',
      '-preset', 'veryfast',
      '-crf', '18',
      '-pix_fmt', 'yuv420p',
      '-b:v', '500k',
      '-bufsize', '600k',
      '-vprofile', 'baseline',
      '-tune', 'zerolatency',
      '-s', '1280x720',
      '-r', '30',
      '-g', '60',
      '-f', 'rawvideo',
      '-',
    ]);
```

I also made sure NAL seperator is presented in the buffers that are sent to the app, and made sure that they're of type Uint8Array when provided to the decoder. When I save the ffmpeg stream to a file everything appears to be fine without any glitches, so I suspect it has something to do with the way I transport the data. Any suggestions? Your help would be very appreciated.

**Comment by soliton4** [comment]
you need to feed complete and discrete nal units to broadway
the nal units are seperated by 00 00 00 01

all the examples in this project do it
