### ISSUE TITLE
The good command ffmpeg stream

### ISSUE THREAD

**Issue by Gamepigeek** [mbebenita/Broadway#222]
hello, I made a nodejs server that receives the frame from ffmpeg, but I can't find the right ffmpeg command that works with BroadWay to stream my  /dev/video0

 ffmpeg -i /dev/video0 -c:v h264 -preset fast -profile:v baseline -f rawvideo  http://mywebsocketserver:8081

almost works but it gives : https://ibb.co/8M8f81f

how can I do ?

**Comment by soliton4** [comment]
https://github.com/mbebenita/Broadway#encoding-video

this should work

**Comment by Gamepigeek** [comment]
doesn't work for /dev/video0
