### ISSUE TITLE
Capture a screen shot from broadway canvas

### ISSUE THREAD

**Issue by kaushikjeet** [mbebenita/Broadway#231]
Hi there,

We would like to capture screenshot from Broadway canvas, but due to webgl rendering it comes black most of the time. To address this issue we have added handler in Broadway player to get callback between frames rendering. that allow us to capture canvas consistently.

Please advise if there is better way of doing this, also help us to know about changing Broadway code is okay with license terms.

Thanks,
Jeet

**Comment by soliton4** [comment]
you probably have issues with your gpu driver
