### ISSUE TITLE
"click me" hint on demo

### ISSUE THREAD

**Issue by soliton4** [mbebenita/Broadway#24]
http://bkw.github.io/Broadway/storyDemo.html

i believe i am not the only one stupid enough to not click on the screen and wonder why it doesnt work

a "click me" message or something similar would be helpful. also it should not be much effort to implement ;)

thx
great project

**Comment by soliton4** [comment]
@bkw what do you mean?

**Comment by bkw** [comment]
Nothing important. I just hoped two commercial projects depending on Broadway would also have resulted in some pull request with their enhancements and fixes and so forth. Never mind.

**Comment by soliton4** [comment]
ah yes i see
that would be nice

hear that commercial users
yeah i am talking to you ;p

**Comment by soliton4** [comment]
@bkw you are hosting the demo sites right?
can you pr the changes you made. i will then update the demo branch to the newest player version.
we need to get the fast worker on the demo site

**Comment by soliton4** [comment]
@bkw i will update the demos and create a new issue for the merge to your repos
