### ISSUE TITLE
Commonjs?

### ISSUE THREAD

**Issue by loyd** [mbebenita/Broadway#25]
What about support *commonjs* and *package.json* for using *browserify*?

**Comment by soliton4** [comment]
i will provide a universal module loader soon

**Comment by loyd** [comment]
@soliton4 Nice!

**Comment by soliton4** [comment]
may i bring your attention to
https://github.com/mbebenita/Broadway/tree/umd/Player

i tested it with amd and it works fine

Player, Decoder and YUVWebGLCanvas have a unified module definition

if you simply want to play video, require Player.js,

```
require(["./Player.js"], function(Player){
var p = new Player({
  useWorker: true/false,
  workerFile: <defaults to Decoder.js>
});

// these both refer to the canvas node
p.domNode;
p.canvas;

p.decode(<binary>);
```

now that was easy

**Comment by soliton4** [comment]
merged into master

have a look at https://github.com/mbebenita/Broadway/blob/master/Player/Player.js

**Comment by soliton4** [comment]
@loyd  is it working for you?

**Comment by loyd** [comment]
@soliton4 Sorry for waiting. Great work, thx.

Firstly, what about `require('ws')` (`'fs'` etc) in `Decoder.js`? Browserify (and other tools, that parse `require()`) complains about it. I suggest replace `require('ws') with require('' + 'ws')` to make it work. Where it can be done?

Secondly, what about `npm` package? I'm sure you'd be a good maintainer.

**Comment by soliton4** [comment]
the require statements you refer to are part of the emscripten build.
does it prevent your browserify configuration from working?
if you just get warnings i suggest you ignore them.

while i will not argue i would be a bad choice for the job, the question remains: 
what is the npm package supposed to do?

**Comment by loyd** [comment]
Yes, it prevent from working (browserify try include `ws` to bundle).

npm package should include three files (`Player.js`, `Decoder.js` and `YUVWebGLCanvas.js`).

**Comment by soliton4** [comment]
i will try to have a look into it. for now i recommend that you do not include Decoder.js in your build.

in my opinion the purpose of providing the 3 mentioned files is best served within github

**Comment by 131** [comment]
I used Decoder.js in a browserify workflow, and all went just fine. Can you is that you recommend _not_ including it (as it's working fine, really !!) ?

**Comment by soliton4** [comment]
should work now
