### ISSUE TITLE
WebGL fallback

### ISSUE THREAD

**Issue by ssleptsov** [mbebenita/Broadway#26]
Hi, 
Is this correct that webGL need here only to convert YUV image to rgb, right?
So is it possible to convert it to rgb without webGL, by this it will be possible to draw image in 2D canvas, right?

Thanks.

        this.webGLCanvas.YTexture.fill(buffer.subarray(0, lumaSize));
        this.webGLCanvas.UTexture.fill(buffer.subarray(lumaSize, lumaSize + chromaSize));
        this.webGLCanvas.VTexture.fill(buffer.subarray(lumaSize + chromaSize, lumaSize + 2 * chromaSize));
        this.webGLCanvas.drawScene();

**Comment by soliton4** [comment]
@ssleptsov 
@mbebenita 
https://github.com/mbebenita/Broadway/pull/44

**Comment by soliton4** [comment]
webgl auto detection and fallback solution works:
http://mbebenita.github.io/Broadway/storyDemo.html

@ssleptsov

**Comment by soliton4** [comment]
@ssleptsov hasnt been active for month
