### ISSUE TITLE
new worker thread implementation

### ISSUE THREAD

**Issue by soliton4** [mbebenita/Broadway#32]
hi broadway.js i am proud to announce i solved the worker thread problem ;)

pls refer to -> http://updates.html5rocks.com/2011/12/Transferable-Objects-Lightning-Fast

instead of cloning the uint8array you create a local copy in the worker thread and then transfer ownership like shown in the link.
the performance boost is unbelievable.

i also created a multithreading implementation for my application. but it requires that 4 seperate h264 streams exist. 
using this together with the new worker threads i am over 40fps at 720p. ;))))))))

if you wanna try it out use the latest bleeding edge nodemirror commit.

the worker.js implementation in broadway.js will not work out of the box.
if you solve the window dependency i will provide a pull request.
otherwise you can look at my changes and feel free to copy them.

thank you 
me

**Comment by orcaman** [comment]
+1
would also love to benefit from @soliton4 's performance improvement, but not sure how to merge it into my broadway clone.

**Comment by soliton4** [comment]
you asked for it
https://github.com/mbebenita/Broadway/pull/43

@orcaman 
@mbebenita 
@saste 
@bkw

**Comment by orcaman** [comment]
@soliton4 awesome, thanks!

**Comment by samsamm777** [comment]
@soliton4 you mention in your first post about the multithreaded implementation which requires 4 streams. Are those streams the same or are they 'slices'(tiles) of the stream?

**Comment by soliton4** [comment]
@samsamm777 seperate
completely seperate

i split the screen in 4 having one distinct stream for each quarter of the screen

here:

https://www.youtube.com/watch?v=nDuHEMA5uSw

**Comment by samsamm777** [comment]
ahh great. Thats exactly what ive implemented. we tile the stream into 4 or 8 and then just decode each separate stream in a separate worker thread. this gives super fast fps.

**Comment by soliton4** [comment]
yeah but with the webgl implementation you the result rendering will not fit exactly.
thats why i created the asm.js implementation

it runs great in firefox, but in chrome its slightly slower

**Comment by samsamm777** [comment]
interesting. there are some join issues but ive not looked into why they are occuring yet. maybe its the same reason. im going to look further into your implementation.

**Comment by soliton4** [comment]
the opengl implementation uses some hard to get into formular to project a 3d shader on 2d

you wont notice much but if your video is of a desktop (like mine) you will notice some strange pixel errors.
and if you try to join 2 halfs of the desktop together its even more apearant

this is simply a issue of the transformation of the finished rendered frame from yuv to rgb

there are other projects who do a yuv to rgb using webgl. maybe they have a better way to do it. i did not have the time and motivation to get into it. i simply programmed a transformation in asm.js which works fine.

if you could solve this you would get a hero point from me

**Comment by soliton4** [comment]
@mbebenita gave me push rights
so here is the fast worker:
https://github.com/mbebenita/Broadway/commit/cc24730c40033fe590275a9e671498ae2d44cc64
