### ISSUE TITLE
png stream

### ISSUE THREAD

**Issue by hatpick** [mbebenita/Broadway#34]
is there anyway to get a png stream of the video being decoded using broadway, a silly way is to call "toDataURL" on the canvas element every X ms. is it possible?

**Comment by soliton4** [comment]
the canvas is a webgl canvas
i dont know if wegl can be transformed to png

you can use the asm.js implementation. it uses a regular canvas instead
https://github.com/mbebenita/Broadway/pull/44

**Comment by soliton4** [comment]
@hatpick you can now create a Decoder object and pass rgb: true
you get picture decoded in rgb mode, not yuv

have a look at Player.js how to use it to fill a regular non webgl canvas.

that should help getting you pngs
