### ISSUE TITLE
Support H264 Annex B

### ISSUE THREAD

**Issue by rere16** [mbebenita/Broadway#35]
Hello,

I would like to know if this library supports raw H264 Annex B ? if not, is it planned?

Thanks.

**Comment by soliton4** [comment]
i am using raw h264 in my project
https://github.com/soliton4/nodeMirror/blob/edd903a9a75728833da714890e136776796994ff/src/avc/Wgt.js#L291

**Comment by soliton4** [comment]
@rere16 could you tell us if this is still an issue for you?

**Comment by soliton4** [comment]
here is a simple demo using raw h264 data

https://github.com/soliton4/BroadwayStream
