### ISSUE TITLE
HTTP Streaming

### ISSUE THREAD

**Issue by jadbox** [mbebenita/Broadway#38]
I thought I'd put this here to let people know I'm working (in my branch) on changing mp4.js to support progressive downloading of a h.264/ac file from a remote server, as currently the whole file needs to be loaded. Live streaming will not be in scope however. Let me know if you have any questions! Once completed, I'll throw up a pull request.

**Comment by jadbox** [comment]
Anyone want to help me make this a proper pull request? Probably needs a little refactoring to work with the current master.

**Comment by saimamahmood** [comment]
Hi, I was looking at your implementation of Broadway to see if it allows me to synchronize multiple video canvas', frame by frame. I am eventually using this to synchronize multiple video streams from a server. What part of the code should I be looking at to help me achieve this. Currently when i have more than one div of the Broadway class, only the last div seems to be playing the video. Thanks in advance!

**Comment by soliton4** [comment]
@saimamahmood some of the broadway builds are using global variables due to potential speed gains.
i am not certain about the current build thou.

best way to avoid this problem is to use worker threads. i provided a fast worker thread implementation that works on ff and chrome. 
https://github.com/mbebenita/Broadway/pull/43

i am not sure about the current usability of the main branch. but if you follow my instructions you can get several fast workers up and running.

**Comment by soliton4** [comment]
@saimamahmood try using 
https://github.com/mbebenita/Broadway/commit/736e9230f86baae6bdcd98c286aad9cf78e9965b

pls provide feedback how this works for you

**Comment by saimamahmood** [comment]
@soliton4 thanks it works much faster now! I have a few follow up questions that ill post in a new issue.

**Comment by soliton4** [comment]
@jadbox i created a broadway package with umd

could you review it and make a pr based on these sources?

https://github.com/mbebenita/Broadway/blob/umd/Player/Player.js

**Comment by soncodi** [comment]
:+1:

**Comment by soliton4** [comment]
a streaming demo can be seen here:

https://github.com/soliton4/BroadwayStream

**Comment by mbebenita** [comment]
It would be great to setup a live demo for this that doesn't require people to install anything locally.

**Comment by soliton4** [comment]
would be

you have that amount of traffic?

**Comment by jadbox** [comment]
@soliton4 is streaming support now merged into master? Sorry, I lost track of this thread.

**Comment by soliton4** [comment]
@jadbox sorry no explicit streaming support exists.
i will definitely add a function to split a stream into nal units
for the long term i have the idea to make broadway into a custom html5 tag that you can use like a video tag
but thats just an idea right now.

**Comment by Zaithe** [comment]
I have tried using the streaming demo but streaming is not working. Is this what you meant when you said "sorry no explicit streaming support exists" @soliton4 ?  
I'm kind of newb with video player coding but would appreciate some pointers if i am missing something. I expect your stream node app is for a server with SSH support. How would you transport the data? Why doesn't it work without needing a streaming server? HTML5 video player supports playing frames as they buffer without needing a ssh server. It decodes frame by frame so why not just show them while they are downloading?

**Comment by soliton4** [comment]
@Zaithe ssh is not a requirement for the streaming demo.

your why not suggestions make sense for the most part.
so why not program it and make a pr?

**Comment by Zaithe** [comment]
@soliton4 I'll try, any advice to speed things along on how to show frames while it's downloading?

**Comment by soliton4** [comment]
if you have a mp4 streaming is officially not supported by this format as far as i know.

if you have a h264 stream, split it at 00 00 00 01 and feed these chunks to the decoder
