### ISSUE TITLE
emscripten run python error coming

### ISSUE THREAD

**Issue by Pranavindia2007** [mbebenita/Broadway#39]
Hi All,

I am trying to compile FFMPEG  scaling library of android but i am not able to compile.I want  to scale the video.Currently it is taking the video height and width but i want to use it with my size.

Can anybody help me in that?

Thanks,
Pranav Shah

**Comment by soliton4** [comment]
@Pranavindia2007  i just compiled with the latest version of emscripten 1.29.0

pls update your emscripten
also update Broadway to  https://github.com/mbebenita/Broadway/commit/736e9230f86baae6bdcd98c286aad9cf78e9965b

run make.py  
it should work  

if it works pls close the issue - thx
