### ISSUE TITLE
avc-codec.js compiled with latest emscripten displays gray video if compiled with -O2

### ISSUE THREAD

**Issue by saste** [mbebenita/Broadway#40]
I'm compiling the code with the latest version of emscripten (build of the day) and the storyDemo.html demo is displaying gray frames. The onPictureDecoded callback is called regularly. 

If I compile the decoder code with -O1 or -O0 (by editing the Decoder/make.py script) the code is working correctly. When compiled with -O2 the average framerate increases with respect to -O1, but this may be due to the fact that the decoding code is not called. 

Tested with Firefox 30.0 on Linux mint and with Firefox 34.0 on Windows 7.

**Comment by soliton4** [comment]
fixed here:

https://github.com/mbebenita/Broadway/commit/736e9230f86baae6bdcd98c286aad9cf78e9965b
