### ISSUE TITLE
workers=true path not working anymore

### ISSUE THREAD

**Issue by saste** [mbebenita/Broadway#45]
By setting the workers flag to "true" storyDemo.html is not working at all (not generating any content).
Tested with Firefox 34.0 and 30.0 on Linux, with the current master e6d1c4dd9275db323c793f3ca5c2843cb63159fd

This is the log I get from the Firefox console:
>Successfully compiled asm.js code (total compilation time 109ms; not stored in cache) avc-codec.js
"increasing TOTAL_MEMORY to 67108864 to be compliant with the asm.js spec" avc-codec.js:4
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. storyDemo.html
: Successfully compiled asm.js code (total compilation time 212ms; stored in cache) avc-codec.js
ReferenceError: Module is not defined avc.js:5
"MP4Player::readAll()" mp4.js:825
"Parsed stream in 6 ms" mp4.js:457
"MP4Player::readAll(), length: 9064588" mp4.js:831
"creatingTextures: size: (640, 360)"

I think the main problem is related to line:
>ReferenceError: Module is not defined avc.js:5

Tested on various platforms, always getting the same result.

**Comment by saste** [comment]
After more tests, I'm not sure anymore it ever worked.

Changing this in Decoder/library.js:
```javascript
var LibraryBroadway = {
  broadwayOnHeadersDecoded: function () {
      window["_broadwayOnHeadersDecoded"]();
  },
  broadwayOnPictureDecoded: function ($buffer, width, height) {
      window["_broadwayOnPictureDecoded"]($buffer, width, height);
  },
};
```
to:
```javascript
var LibraryBroadway = {
  broadwayOnHeadersDecoded: function () {
      _broadwayOnHeadersDecoded();
  },
  broadwayOnPictureDecoded: function ($buffer, width, height) {
      _broadwayOnPictureDecoded($buffer, width, height);
  },
};
```
the code is working in both paths (`workers=true` and `workers=false`) but **only** with -O1 in make.py, with -O2 the code won't work.

**Comment by samsamm777** [comment]
Do you have any idea why the avc.js reference only occurs when its used in the worker? It doesnt error when not using workers.

It seems its down to it being includes with importScripts('avc.js') any ideas why it doesnt work this way?

**Comment by saste** [comment]
@samsamm777, I don't think it is related to the importScripts() but rather to how the Module dependencies are loaded (it will fail if you compile with -s ASSERTIONS=1 and -O1, will work with -s ASSERTIONS=0 and -O1). Still investigating about the problem.

**Comment by saste** [comment]
@samsamm777, maybe related to --closure 1. With --closure set to 0 in Decoder/make.py, I got no Module reference error, but unfortunately in this case the decoder doesn't seem to decode :-( (--closure 0 and -O1 seems to work OTOH).

**Comment by soliton4** [comment]
fixed by
https://github.com/mbebenita/Broadway/commit/cc24730c40033fe590275a9e671498ae2d44cc64

**Comment by saste** [comment]
I confirm this looks fixed in latest version, thanks.
