### ISSUE TITLE
Video decoding issue

### ISSUE THREAD

**Issue by Pranavindia2007** [mbebenita/Broadway#46]
Hi,

I have h264 main profile encoded mp4 file.When i use this file decode is not able to  decode the video on the browser.If i use the Mp4 file with H264 base line profile encoded video.Decode is able to decode the video.

Is there anything special to provide ?

Help please....

Thanks,

Pranav Shah

**Comment by samsamm777** [comment]
only the baseline profile(66) is supported by the decoder.

**Comment by Pranavindia2007** [comment]
Hi,

Is there any way to enable main profile to decode?

Like recompiling the ffmpeg of android or anything else?

Thanks

Pranav Shah

**Comment by saste** [comment]
Pranav, no there is no way to fix it. Broadway depends on the Android H.264 decoder, indeed it is based on an emscripten conversion of that C++ code (which is not based on FFmpeg), so it only supports the features of the Android H.264 decoder included in the sourcecode.

**Comment by Pranavindia2007** [comment]
Hi,

Sorry for the late response.Ya it seems that android support the main profile of h264 we just need to provide the argument for that. I am trying but no luck So can any one just share the command arguments to compile the ffempeg using emscriptopn? 

Thanks,

Pranav Shah

**Comment by saste** [comment]
> So can any one just share the command arguments to compile the ffempeg using emscriptopn?

Converting ffmpeg to JS is outside the scope of this project. About Android decoding, check in the src directory the decoder source code. It is not very clear how the code was obtained, but you could try to update it, assuming the latest version of the code supports H.264 main profile decoding. But I couldn't tell you the first thing about updating that code (indeed it is not very clear how the current decoder C code was obtained).

Alternatively, you should consider an entirely different project relying on another H.264 decoder.

**Comment by mbebenita** [comment]
The code should be available in the Android source tree.

**Comment by Pranavindia2007** [comment]
Hi,

ya true.I have used android code only but not able to compile in main profile of H264.

Can anybody show me the arguments to compile that code using emscripton ?

I am trying since many days.

Thanks

Pranav Shah

**Comment by Pranavindia2007** [comment]
Hi Developers,

Any help please ?

Thanks

Pranav Shah

**Comment by saste** [comment]
@Pranavindia2007, can you show any evidence that latest version of Android decoder supports the H.264 main profile?

About extracting the H.264 decoder code from Android, that's probably a not trivial operation, and maybe Michael can give you some indications since he's the guy who did it the first time.

**Comment by soliton4** [comment]
@Pranavindia2007 at the start page of this project is a ffmpeg example
it works as well with avconv

https://github.com/mbebenita/Broadway/blob/master/README.markdown

you can use this to encode your video in a format that is usavle for Broadway.

if you need stream data, you can configure x264 to use extremely low latency. so you could transcode on the fly without introducing more than 1 - 2 frames of latency.

if you need help with this i can provide more infos

**Comment by soliton4** [comment]
@Pranavindia2007 as you can see ppl are willing to help you.

do you still need help?

**Comment by Pranavindia2007** [comment]
Hi,

Thank you all you support and help.

It seems that android ffempeg does not support main profile.

anyboday knows about this?

**Comment by soliton4** [comment]
yes broadway supports only a subset of the h264 spec

refer to the readme file for a ffmpeg example to create usable video data
