### ISSUE TITLE
Implementing Multiple Broadway Canvas' for Displaying Synchronized Video

### ISSUE THREAD

**Issue by saimamahmood** [mbebenita/Broadway#54]
Hi, 

I am trying to use Broadway to implement multiple canvases such that the video frames from each canvas is synchronized. I'm not sure what part of the code i need to alter in order to achieve this.  

Also to test the synchronization of frames i made an mp4 video from images consisting of numbers 1-100, using ffmpeg. When i test the demos using this mp4 file, there is nothing displayed. Is there something that im missing?

Help will be appreciated!

Thanks!

**Comment by soliton4** [comment]
@saimamahmood pls have a look at the front page of this project

https://github.com/mbebenita/Broadway

there is a example commandline for ffmpeg. it works as well with avconv.
you have to include those parameters in order to make the video decodable by this lib.

as for the synchronization, are we talking about 2 times the same video or different videos?

**Comment by saimamahmood** [comment]
I used the command line options, but only the first frame from the video is displayed. It stops at that.

As for the synchronization, it is for the same video. Im using this numbered video, to check if the same frame is being displayed across the multiple canvases.

**Comment by soliton4** [comment]
i have no experience with image to video encoding. guess you have to study the manual ;(

as for the videos, imply add another canvas here:
https://github.com/mbebenita/Broadway/blob/master/Player/mp4.js#L816

**Comment by saimamahmood** [comment]
So i should create another canvas element with the same video source after this line right?

**Comment by soliton4** [comment]
here:
https://github.com/mbebenita/Broadway/blob/master/Player/mp4.js#L851

the canvas is created

here:
https://github.com/mbebenita/Broadway/blob/master/Player/mp4.js#L824

a frame is being drawn

if you simply create a 2nd canvas
and fill it with the same frame data you will have 2 canvases that are showing the same video

**Comment by saimamahmood** [comment]
Thanks for the reply, I had figured it out :)

**Comment by soliton4** [comment]
but i dont get why you would like to have the same vid. twice
does it make any sense?

**Comment by saimamahmood** [comment]
I need to show that the video frames are indeed being decoded and displayed at the same time. As the first step. Now i need to extend it to work with 2 different videos.

**Comment by soliton4** [comment]
you will need to create 2 workers

each with its own onpicdecoded function and its own canvas

**Comment by soliton4** [comment]
have a look at 
https://github.com/mbebenita/Broadway/blob/umd/Player/Player.js

its broadway with a umd. the usage note in front of the file should say it all

you can use it to have 2 or more broadway instances, regardless if you use worker or not.

**Comment by soliton4** [comment]
the latest version has full support for several instances.

**Comment by saimamahmood** [comment]
Hi i wanted to clarify, what is the difference between using a worker and not using one?

**Comment by soliton4** [comment]
@saimamahmood this should be helpful to you
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers
