### ISSUE TITLE
problems with x11grab

### ISSUE THREAD

**Issue by soliton4** [mbebenita/Broadway#60]
hi @mbebenita 
broadway refuses to render the output of this:
```
ffmpeg -y -f x11grab -r 30 -s 1920x1080 -i :0+0,0  -b:a 2M -bt 4M -vcodec libx264 -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -an -f h264 -s 1920x1080 screentest2.h264
```

if i do the same thing with avconv it works

also strange: regular file transcoding works fine with ffmpeg + broadway

do you have any idea / hint why?

**Comment by shi-yan** [comment]
I think the reason it doesn't play is that the video is in high profile.

I wrote a tool https://github.com/shi-yan/H264Naked to look at the h264 packets, the video generated with the above command has profile_idc == 244 

244 is the high profile:
#define FREXT_Hi444   244

see
http://iphome.hhi.de/suehring/tml/doc/ldec/html/defines_8h.html#aa63417df3698a4fac79fb16a58f6091

the broadway decoder is very limited, can only decode baseline profile.

**Comment by soliton4** [comment]
thank you for the information. 
can you tell me how i can switch to another profile in ffmpeg?

**Comment by shi-yan** [comment]
here https://trac.ffmpeg.org/wiki/Encode/H.264

search "choose a preset" on that page

**Comment by soliton4** [comment]
thank you again @shi-yan 
i feel like i could have found that myself using google. which i actually did. 
but you know how it is with the github issues. you just ask since you are there already.

well thx again.
