### ISSUE TITLE
WebGL issue

### ISSUE THREAD

**Issue by kompsale** [mbebenita/Broadway#63]
Hi, I have an issue in Chrome and Firefox when decoding frames with webgl set to "auto" or true.

My code:

<script src="broadway/Player.js"></script>
<script src="broadway/Decoder.js"></script>
<script src="broadway/YUVWebGLCanvas.js"></script>
<script>
var player=new Player({
  useWorker: true,
  workerFile: "broadway/Decoder.js",
  webgl: "auto"
});
document.body.appendChild(player.canvas);

while(1) {
  ---Feed h264 frames in_h264 buffer---
  player.decode(hit_h264);
}
</script>

Chrome says exception is in Player.js line 119:
self.webGLCanvas = new YUVWebGLCanvas(self.canvas, self._size);

Firefox says exception "TypeError: YUVWebGLCanvas is not a constructor" on Player.js:119:27

When I use "webgl:false" option video plays ok.
Also when "webgl:"auto" or true, canvas resize to video size, but when "webgl:false" it's just stays as it is by default (does not adapt size to video frame size).

Please advise if someone experienced the same?

**Comment by soliton4** [comment]
you are missing this file
https://github.com/mbebenita/Broadway/blob/master/Player/YUVWebGLCanvas.js

**Comment by kompsale** [comment]
I'm not. I have this file included via <script src=>

**Comment by kompsale** [comment]
Solved!
script src="broadway/YUVWebGLCanvas.js" /script
must be first included in html
Thanks!

**Comment by soliton4** [comment]
@kompsale i recommend using a amd or common.js loader
