### ISSUE TITLE
upscale canvas

### ISSUE THREAD

**Issue by sauerhoefer** [mbebenita/Broadway#64]
hi @all,

first congratulations to the team for this awesome piece of code! I was able to build a working prototype within hours.

My h264 data is send from a mobile phone via a websocket server to the browser. Right now I want to upscale the canvas on the html page,  I tried to set the  width and height of the element, which works fine until new data is drawn.

Is there a trick how to upscale the canvas?

many thanks in advance,
axel

**Comment by mbebenita** [comment]
@sauerhoefer have you tried setting the CSS `width` and `height` attributes instead of the Canvas `width` and `height`?

**Comment by sauerhoefer** [comment]
oh wow, that was to easy :) :+1:
