### ISSUE TITLE
Is it possible to track the current time of the video playing?

### ISSUE THREAD

**Issue by chaitanyapro** [mbebenita/Broadway#66]
I wanna track the time of the frame being displayed in the canvas? Also is ti possible to limit the number of frames rendered per second?

**Comment by soliton4** [comment]
broadway.js is at this moment only a decoder. you can use it to decode your h264 stream.
if you decide to render the frames, count them or do what ever you like with them is up to you.

use 
https://github.com/mbebenita/Broadway#decoderjs
to decode the stream
you can pass the rgb parameter to get the frames in a rgb format.
