### ISSUE TITLE
Possible to Integrate Canvas Event Handlers 

### ISSUE THREAD

**Issue by saimamahmood** [mbebenita/Broadway#67]
Hi, 

I am trying to see if its possible to add event handlers on the canvas such that will allow for canvas manipulations. For instance I have implemented zooming and panning, using the mousemove event listeners etc,  functions using the canvas context and SVG matrix separately outside of Broadway. I am now trying to integrate this with Broadway, but i seem to be running into problems. 

What is the best way to achieve this? What part of the code should i look at to effectively integrate this functionality?

Thanks!

**Comment by mbebenita** [comment]
Broadway decodes video content into a raw typed array buffer in YCbCr format. There is a conversion pass to RGB and then finally the buffer pushed to a canvas using `putImageData()`. You probably just need to keep two canvases around. Use one canvas to upload the video buffer, and another where you set the transform and use `drawImage`.

**Comment by soliton4** [comment]
you can pass render: false to the player to disable the internal rendering function

the onPictureDecoded function of the player is called anyway and you can overwrite it with your own implementation

if you want to dig deeper i just created a foundation for a frame buffer here:
https://github.com/mbebenita/Broadway/commit/0324cb3a319441bc04d3e132a05e77fdec978deb
