### ISSUE TITLE
Examples for beginners

### ISSUE THREAD

**Issue by activeG8** [mbebenita/Broadway#68]
Hello,

1) How do I use Decoder to override onPictureDecoded?
2) Do I have to include Decoder.js only? Or all other js files are required as well?
3) What input data Decoder expect? Is preloaded binary mp4 file ok?

Can't get it to work and that is why I decided to write these questions here..
Thanks for your efforts in Broadway.js

**Comment by activeG8** [comment]
I've preloaded mp4 video file as a binary data and pass it to Decoder's decode() method.
But onPictureDecoded is not called at all and I don't see any error in the console.

var dd = new Decoder();
dd.onPictureDecoed = ddOnPictureDecoded;		
dd.decode(queue.getResult('idlevid'));

**Comment by activeG8** [comment]
Converted ArrayBuffer to byte array and passed it to decode() method.
Now its telling me that "The source is too big".
Can you please sched some more light on the input data requirements.
Should it feed decode method in chunks maybe? If so then what are the limits?

var arr = queue.getResult('idlevid');
var byteArray = new Uint8Array(arr); 

var dd = new Decoder();
dd.onPictureDecoded = ddOnPictureDecoded;
dd.decode(byteArray);

**Comment by activeG8** [comment]
How do I use it to decode H.264 into pictures?

**Comment by mcranston18** [comment]
@activeG8  The way I got started:

1. clone the Broadway repo
2. go into the `Player` folder and run a server to start it
3. Take a look at the `storyDemo.html` and begin playing around with it. Notice how in this file the `Broadway` plugin is initialized?

```
var broadway = new Broadway(elm);
broadway.play();
```

Replace the source code of one of their videos with one of yours and see if it works

**Comment by jncheech** [comment]
@activeG8 have you been able to decode h.264 into pictures? I'm trying to do the same thing.

**Comment by activeG8** [comment]
Here is how I got it to work for me:

	function onComplete()
	{
	this.avc = new Decoder({
	        rgb: true
	      });
		this.avc.onPictureDecoded = ddOnPictureDecoded;
	
	this.reader = new MP4Reader(new Bytestream(queue.getResult('idlevid'))); // queue.getResult('idlevid') is my preloaded binary video
        this.reader.read();
        var video = this.reader.tracks[1];
        this.size = new Size(video.trak.tkhd.width, video.trak.tkhd.height);
        console.info("MP4Player::readAll(), length: " +  this.reader.stream.length);
		
	  var video = reader.tracks[1];
      var audio = reader.tracks[2];

      var avc = reader.tracks[1].trak.mdia.minf.stbl.stsd.avc1.avcC;
      var sps = avc.sps[0];
      var pps = avc.pps[0];

      /* Decode Sequence & Picture Parameter Sets */
      this.avc.decode(sps);
      this.avc.decode(pps);

      /* Decode Pictures */
      var pic = 0;
      setTimeout(function foo() {
        var avc = this.avc;
        video.getSampleNALUnits(pic).forEach(function (nal) {
          avc.decode(nal);
        });
        pic ++;
        if (pic < 3000) {
          setTimeout(foo.bind(this), 1);
        };
      }.bind(this), 1);
	}

	function ddOnPictureDecoded(mx, width, height)
	{	
		var imgData = tCtx.createImageData(width, height);
		imgData.data.set(mx);    
		tCtx.putImageData(imgData, 0, 0);
	
		var imgUrl = tCanvas.toDataURL(); // <= here is your image encoded to Base64 string (PNG)
		var image = new Image();
		image.src = imgUrl; 		
	}

**Comment by activeG8** [comment]
Also keep in mind that you have to decode your video to mp42, Baseline Level 2.1

**Comment by jncheech** [comment]
@activeG8 thanks for your reply man. where and how is "onComplete()" being called?

**Comment by jncheech** [comment]
@activeG8 and thanks for your note about baseline...i had to figure that one out myself too. used ffmpeg to compare stats on the sample videos and the video i was using to test. I'm no video format expert either :)

**Comment by activeG8** [comment]
onComplete is called upon completion of loading the video file

**Comment by soliton4** [comment]
@jncheech if you dont want to go through the trouble of creating a website that loads a video and all you can just play arround with this:

https://github.com/soliton4/BroadwayStream

**Comment by soliton4** [comment]
if you guys have examples you want to share with the rest of the world feel free to send them to me or better make a pull request

lets make the world a better place ;)

**Comment by Laubeee** [comment]
Thanks, @activeG8 for the sample, it helped a lot getting started. However, if speed is of the essence, you really shouldn't loop using setInterval. Most browsers have (on purpose) a minimum delay of 4ms. Instead you can just use a regular while loop. It cut my decoding time in half.
