### ISSUE TITLE
CORS error when trying to play an external video

### ISSUE THREAD

**Issue by mcranston18** [mbebenita/Broadway#70]
I copied the repository but I am having issues when I try to load in an external video, I get a CORS error from Broadway:

```
XMLHttpRequest cannot load http://www.w3schools.com/html/mov_bbb.mp4. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

However, I am able to play that same URL (`http://www.w3schools.com/html/mov_bbb.mp4`) when I just use a video tag. I am using `storyDemo.html` and here is my code:

```
// this will throw a CORS error
<div class="broadway" src="http://www.w3schools.com/html/mov_bbb.mp4" width="640" height="360" style="float: left; position: relative;" workers="false" render="true" webgl="auto"></div>

// this will play as expected
<video src="http://www.w3schools.com/html/mov_bbb.mp4"></video>
```

Is there a reason why an external video would get a CORS error from Broadway but not when I just try to play the video as is?

**Comment by soliton4** [comment]
this is not a broadway related issue. and i must admit i dont know enough about CORS to give advice
please refer to the experts at stackoverflow
