### ISSUE TITLE
Video freezes on 1st frame

### ISSUE THREAD

**Issue by activeG8** [mbebenita/Broadway#72]
I converted video as suggested in the Readme file:
ffmpeg -y -i sourceFile -r 24 -b:a 2M -bt 4M -vcodec libx264 -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -an targetFile.mp4

But it won't play full video, just showing the first frame and then freezes. No errors in browser console.

Here is a MediaInfo on the converted file:

General
Complete name                            : C:\ffmpeg\targetFile.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 231 KiB
Duration                                 : 1s 84ms
Overall bit rate                         : 1 746 Kbps
Writing application                      : Lavf56.30.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L3
Format settings, CABAC                   : No
Format settings, ReFrames                : 1 frame
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1s 84ms
Bit rate                                 : 1 740 Kbps
Width                                    : 640 pixels
Height                                   : 472 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 24.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.240
Stream size                              : 230 KiB (100%)
Writing library                          : x264 core 146 r2538 121396c
Encoding settings                        : cabac=0 / ref=1 / deblock=1:0:0 / analyse=0x1:0 / me=dia / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=3 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=250 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00

**Comment by activeG8** [comment]
H.264 Profile was the issue. Broadway doesn't work with High Profile. It was not stated anywhere in the docs.

**Comment by shi-yan** [comment]
exactly. I was also hit by the same missing information. the doc does say it doesn't support entropy encoding and weighted prediction. but I guess only very experienced h264 engineers would understand that means no high-profile.

**Comment by soliton4** [comment]
@shi-yan @activeG8 you seem to know more about h264 insides than me. which isnt hard cause im still very much a noob.

maybe you can help me with this?
https://github.com/mbebenita/Broadway/issues/60

i would very much apprechiate your input

**Comment by soliton4** [comment]
@shi-yan @activeG8 no idea?

**Comment by PatrikGallik** [comment]
I had the same issue, but the problem was missing audio track in the video. Adding empty audio track solved the issue.

**Comment by soliton4** [comment]
the mp4 parser is just a hack.
if you want add a more flexible parser or dont use it at all
