### ISSUE TITLE
Convert decoded frames to Base64/png string

### ISSUE THREAD

**Issue by activeG8** [mbebenita/Broadway#73]
I'm using Decoder only to decode video file into frames. My next step is to convert each frame to Base64 string (PNG).

Currently I'm doing it using canvas and toDataUrl() method of the canvas. 
Is there any other more optimal solution for it? I'm not sure drawing onto the canvas and then fettching the picture back is a good one approach in terms of performance.

	function ddOnPictureDecoded(mx, width, height)
	{
		var imgData = ctx.createImageData(width, height);
		imgData.data.set(mx);    
		ctx.putImageData(imgData, 0, 0);
		
		var imgUrl = canvas.toDataURL(); // <== Base64 encoded PNG string here
	}

**Comment by soliton4** [comment]
if you need it in png encoded, the way you posted is probably the best.

if you need raw rgb data you can pass rgb: true to the decoder constructor. see https://github.com/mbebenita/Broadway#options-1

you will get a raw rgb data you can use for putImageData or use it for what ever you need

**Comment by activeG8** [comment]
Thanks for the quick reply!

Yes, I use this flag already. Otherwise I get YUV raw data which is not showing properly on the screen later.

**Comment by soliton4** [comment]
then i would say you are doing it right

**Comment by activeG8** [comment]
Ok, thank you!

**Comment by soliton4** [comment]
@activeG8 i added the option 
preserveDrawingBuffer
you can pass this option with a value of true to the Player constructor. it will create the webgl context with 
preserveDrawingBuffer: true

in theory you should be able to get the png data via 

player.canvas.toDataURL("image/png");

i didnt try to display the output yet but this
http://stackoverflow.com/questions/15558418/how-do-you-save-an-image-from-a-three-js-canvas
says it should do the trick

**Comment by soliton4** [comment]
@activeG8 did you try it?
