### ISSUE TITLE
Looping a video in Broadway?

### ISSUE THREAD

**Issue by mcranston18** [mbebenita/Broadway#74]
Is it possible to have the video play on `loop` after triggering `broadway.play()`?

**Comment by soliton4** [comment]
you mean the play function in the mp4 parser? 
i still consider the mp4 file to be more part of the demo than the core project.
but so many ppl ask for features here maybe someone should write an actual video player.

**Comment by mcranston18** [comment]
@soliton4 Yes. If I have a few seconds video that I want to decode, is doing so possible?

Also, does the Broadway object time elapsed and total time of the decoded video?

**Comment by soliton4** [comment]
broadway is at the moment only a decoder. a very fast one considering its js but still, just a decoder.
the Player.js is not actually a complete video player in that sense, it just provides functions to render decoded frames to a canvas.

if you only have a few seconds, use Player.js, initialize it with render: false and override the onPictureDecoded function.
that way you can collect all the frames.
you can then use the new createCanvasObj and renderFrame functions to display your video. the timing and everything else you need to program yourself.

if you want you can create something reusable to contribute to broadway ;)

**Comment by mcranston18** [comment]
@soliton4 Thanks for the tips. I'll give it a shot and if I can get it working properly, I'll contribute
