### ISSUE TITLE
playing h264 stream

### ISSUE THREAD

**Issue by kompsale** [mbebenita/Broadway#75]
Hi,
I transmit baseline h264 stream from camera over websocket into browser.
When I first connect websocket and then run camera to produce h264 stream all works fine - broadway renders video just fine.
But when I first run camera and then connect to running video stream I cant see any frames rendered.
Is there any trick to render frames when connecting "in the middle" of h264 stream?

Thanks for great project!

**Comment by soliton4** [comment]
pls be aware that this is no expert advice.

you should keep the first 2 or 3 nal units from the camera stream. if your resolution doesnt change there is a chance that the first 2 nals are gonna be identical.

they are used to tell the decoder what resolution your stream is encoded in.

**Comment by kompsale** [comment]
Many thanks. Solved.

**Comment by soliton4** [comment]
so it actually works with keeping the first nal units? cause i have never tried that out

**Comment by kompsale** [comment]
I have an option to add picture parameter set headers to h264 stream, this solves an issue with rendering.

**Comment by wenxingxing** [comment]
how did you set the encoder, i'm stucked here. i'm using libx264. how to set it to the baseline mode?

**Comment by soliton4** [comment]
@wenxingxing you probably need to study the libx264 documentation. i am using libx264 through avconv. the profile is a commandline parameter that is passed along to the lib.
