### ISSUE TITLE
Chrome size question

### ISSUE THREAD

**Issue by orcaman** [mbebenita/Broadway#77]
Hey there,

Amazing project. Question: on the onPictureDecoded function, the luma size is set to the width * height, and the chroma size is set to 1/4 of that (>>2). Is this because of the chroma subsampling on H264? If so, according to what ratio the chroma size determined? I understand that the common one for H264 is 4:2:0, and anyway, I can't find a standard ratio where the chroma is 1/4 the size of the luma (on 4:2:0 is 1/2, right?).

Thanks!
Or

**Comment by mbebenita** [comment]
Perhaps it's referring to the size of only one of the chroma channels, which would be 1/4 of the luma channel.

**Comment by orcaman** [comment]
Oh, I was missing the part about sampling the chroma only on alternate lines. So in face there is indeed 1 chroma value for every 4 luma values, not for as as I initially thought. Thanks for your quick reply.
