### ISSUE TITLE
convert jpgs to mp4 couldn't play by broadway

### ISSUE THREAD

**Issue by wangniancai** [mbebenita/Broadway#81]
Hi ,

    I'm new starter, when use  ./ffmpeg -y -i ./jpgs/0_%d.jpg -r 30000/1001 -b:a 2M -bt 4M -vcodec libx264 -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -an targetFile.mp4 , without audio ,
    just can play firt frame, could y please do me a favor, thanks a lot.

**Comment by soliton4** [comment]
try h264 as output format and split the output into nal units

**Comment by wangniancai** [comment]
Hi Soliton4,

the below is my command :

./ffmpeg -y -i ./jpgs/0_%d.jpg -r 30000/1001 -b:a 2M -bt 4M -vcodec libx264
-pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -an targetFile.mp4

I changed the output format h264, It also can't play

I put the resoruces in the attachment , could you please do me a favor

cheers
niancai




2015-07-25 21:00 GMT+08:00 soliton4 <notifications@github.com>:

> try h264 as output format and split the output into nal units
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbebenita/Broadway/issues/81#issuecomment-124844946>.
>



-- 
Best Regards

Wang Niancai
Mobile: +86 13911517702

**Comment by wangniancai** [comment]
split the output into nal units ? actually I did not understand

**Comment by soliton4** [comment]
a nal unit begins with 00 00 00 01
split your stream at this positions and feed only the resullting nal units

**Comment by wangniancai** [comment]
Hi soliton4,

     I found that /ffmpeg -y -i ./jpgs/0_%d.jpg -r 30000/1001 -b:a 2M -bt 4M -vcodec libx264
-pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -an targetFile.mp4 ,I put audio track can play now , so  I create a new issue for you , It might be some decoder suggestion is not strong engouh

**Comment by soliton4** [comment]
did you try playback without the mp4 module?

**Comment by wangniancai** [comment]
yes H264， but It did not work， could you please send me a email, I can send you the file I made, you can debug it , cheers

**Comment by wangniancai** [comment]
ffmpeg.exe -y -i v0.mp4 -i _s1.mp4  -shortest _v0.mp4

I just used the file convert from jpg and mix your demo tree.mp4 ,it can play

**Comment by soliton4** [comment]
so its resolved?
if so pls close the issue
