### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by aizawak** [mbebenita/Broadway#83]
I seem to be getting a significant amount of memory usage, especially from JSArrayBufferData for a ~15mb clip (see below). I was wondering if you could help direct me towards a solution, if you believe there could be a leak in Decoder.js? I am deleting the decoded frames immediately after they are rendered, so I have narrowed down the leak to either MP4Reader or Decoder.

![screenshot 24](https://cloud.githubusercontent.com/assets/10719764/9204776/a778a942-402c-11e5-93e2-588aaaca091c.png)

**Comment by soliton4** [comment]
i do not recommend using the current implementation of mp4 reader for a productive environment.
it will put your mp4 in array buffer chunks and most likely not free them.
think of mp4 reader as a example implementation.
player.js and decoder.js have very good memory management.
you can dig in to the new parameters i added but havent fully documented yet, they may help you deal with memory and gc issues
