### ISSUE TITLE
Version and tag of Broadway

### ISSUE THREAD

**Issue by PeterDaveHello** [mbebenita/Broadway#87]
Hi there, I'm Peter from [cdnjs](https://github.com/cdnjs), there is a request ticket wanna we hosting this awesome lib: cdnjs/cdnjs#5706, and I think we can do it, but there is a small problems, we don't know what are the actually versions of Broadway, I didn't see it in the repo(tags and files) and website, not sure if I missed anything, would you mind to help me confirm that? Many thanks!

**Comment by soliton4** [comment]
so you want us to version broadway.js?

**Comment by PeterDaveHello** [comment]
Yes if you agree :smile:

**Comment by soliton4** [comment]
https://github.com/mbebenita/Broadway/releases/tag/0.1.0

**Comment by PeterDaveHello** [comment]
:+1: Will add this lib today!
