### ISSUE TITLE
Adapting Broadway to playback live video streams

### ISSUE THREAD

**Issue by BenjaminXiao** [mbebenita/Broadway#9]
I am trying to get broadway to work with a HTTP live video stream coming from VLC. My goal is to get a webcam feed displayed in the browser without any plugins.

Now I am aware that XHR does not support progressive download and as such does not support live streams. Is there a way around this? I am willing to contribute some development time to get live streaming to work with Broadway as I think it could be very valuable for things like TV streams or videoconferencing solutions. However I need some pointers:
1.) Is live streaming possible at all with Broadway?
2.) Is there an alternative to XHR that lets me do live streaming? I am thinking of using WebSocket and creating a custom streaming server that sends a video stream using it. 
3.) If I do use WebSocket, which areas of the Broadway code do I need to modify in order for it to get the video data?

Thanks!
Ben

**Comment by soliton4** [comment]
@BenjaminXiao 
could you comment on this?
https://github.com/mbebenita/Broadway/pull/44

i wonder if your yuv > rgb conversion is anything like mine

**Comment by soliton4** [comment]
i suppose a streaming example would be helpful to you folks.

i have one in nodeMirror but i guess i should create a dedicated websocket stream example here

**Comment by soliton4** [comment]
have a look at this demo video streaming app

https://github.com/soliton4/BroadwayStream

usage of Broadway is really simple

https://github.com/soliton4/BroadwayStream/blob/master/app/connected.pland

**Comment by soliton4** [comment]
i think this issue is resolved
correct me if im wrong

**Comment by shi-yan** [comment]
I'm trying to achieve the same thing. but I got the same problem. onPictureDecoded function never fires. My video is in annex B format with 00000001 header, and I removed the header. But still the Decoder can't decode a frame. I'm also not using ArrayBuffer :( can't figure out why.

**Comment by shi-yan** [comment]
after debugging, I am able to stream video via Broadway.
The two issues I found were:
1. Broadway can only decode baseline profile video (This matches jvenema's comment), whereas my initial video was in high profile.
2. My hardware decoder generate few nal packets at a time. Previously, I thought it was just one single nal, so I only removed the first header.

However, now I'm facing a performance issue. I'm already using a worker and webgl, but the video playback is less than 10 fps (may be even 5 fps, I didn't really measure it. I'm streaming at 30fps, and I know I receive frames via websocket at the same speed. it is really decoder slowness). This behavior doesn't seem to match the broadway demo. I don't know what's wrong?! My video is a 720p video. I generated a mp4 file out of my video stream and switched broadway demo video with it. The performance wasn't that bad.

**Comment by shi-yan** [comment]
Ha, figured out part of the slowness issue by reading the demo code. This did the trick:
            // buffer needs to be copied because we give up ownership
            var copyU8 = new Uint8Array(buffer.length);
            copyU8.set( buffer, 0, buffer.length );
            
            // only post the buffer (slightly faster)
            // add 2nd parameter to indicate transfer of owner ship (this it was makes this worker implementation faster)
            postMessage(copyU8.buffer, [copyU8.buffer]);

I'm not that experienced with javascript. I don't actually quite understand the last line's syntax. I guess javascript has some internal locking mechanism.

**Comment by mbebenita** [comment]
`postMessage` clones the entire object graph reachable from the first argument using an algorithm called structured clone. To avoid cloning large buffers, `postMessage` optionally takes an array of object references that can be transferred, rather than copied. That's what the `[copyU8.buffer]` does.

**Comment by defunctzombie** [comment]
Great issue to read along with. Could someone who got this working clarify if I can pass in bytes with the NAL header `00 00 00 01` or if I need to strip those away before calling `decode`?

**Comment by samsamm777** [comment]
You need to strip them away if I remember rightly.

**Comment by soliton4** [comment]
@defunctzombie you have to pass a complete annex b nal unit to decode
starting with 00 00 00 01
base profile only

**Comment by defunctzombie** [comment]
@soliton4 reading the Decoder.js source comments, seems that I can also pass a buffer with several NAL units (which seems to work). However, what is unclear to me is whether I can split a NAL unit across separate calls to `decode()` or if the buffer I pass to decode must contain a full NAL unit (or several full NAL units) versus parts of a NAL unit to be re-assembled internally.

**Comment by soliton4** [comment]
to ensure relyable decoding i recommend to only pass 1 complete  nal unit to decode
split it up if you have to.
passing incomplete nals will definetly not work

**Comment by 131** [comment]
For live streaming, the easiest way might be to use a nodejs server that connect to the remote source, split the incoming stream on each nal unit and send thoses units to Broadway through websockets.
I wrote a dummy project that does just that and it's very efficient ! https://github.com/131/h264-live-player

**Comment by nagesh1044** [comment]
Hi,
How to increase the performance of java script broadway h.264 encoder library. I am able to decode frames and drawing but seems looking very slow and there is 3 or 4 seconds lag is there. Please let me know is there any options to increase performance of broadway decoder.

**Comment by rdaum** [comment]
To revive this old thread, I have a question -- 

Just to be clear, has _anybody_ managed to get OpenH264 to produce a frame that Broadway likes? When I submit NAL units produced by OpenH264 to Broadway's .decode my callback is never triggered. On paper it sounds like it should work, as it's set up to use baseline profile . Here's what ffplay says about my encoded stream during playback of the same frames:
   
Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 1200k tbn, 50 tbc

I am submitting the NAL units, with or without the 00 00 01 style header, to the decoder and the callback never triggers. I also get no error message (though it seems like Broadway never does that anyway)

If anybody has gotten this to work, how? Maybe there's some set of parameters to OpenH264 I can give to encode in a way that Broadway will tolerate?

**Comment by soliton4** [comment]
@rdaum yes i have actually done that. not sure why you failed. try debugging the c++ sources in a dev env like visual studio or qt

**Comment by rdaum** [comment]
Well, sure, debug to look at what? :-)  Are you suggesting attempting to use the original non-emscripted Android C++ sources to play it back instead?  That would be quite difficult in my environment, but I could do that as a last resort.  Do you have examples of the code you used to encode? Mine is dead-simple, so I'm not sure what I've done wrong.

**Comment by soliton4** [comment]
since you use openh264 to encode you must have some sort of c / c++ project anyway since it is a c / c++ dll
i suggest use the same environment that you use to encode and feed the stream to the android sources. they are quite self contained and should be easy to add to any c / c++ based project. it will tell you what the problem is with far more accuracy than i can

**Comment by danilogr** [comment]
@rdaum, an easy alternative is to dump your NAL units (using the header 00 00 00 01) on a file, a play it back with `vlc`: `vlc dump.h264  --demux h264`

**Comment by rdaum** [comment]
@danilogr Well, yes I've done that but using ffplay not vlc to play it back and it definitely plays. The issue is figuring out why Broadway won't decode it, as ffmpeg has no issues with it at all. Soliton's advice is to try to decode it with Android's libstagefright, which makes sense, but it will take me a few days to set up an Android environment to do that in :-) 

@soliton4 So you can confirm 100% that you used OpenH264 to encode and were able to playback? Because your example linked above seems to use x264 (which I don't have access to because of licensing). Thanks.

**Comment by soliton4** [comment]
yes i am not refering to that example. i can asure you that i have a working setup that encodes with openh264 and decodes with broadway

**Comment by rdaum** [comment]
Thanks. I got it working. My problem was in the receiving code on the browser side -- the initial key frame was getting lost in the shuffle of receiving payloads due to a logic error. My callback is now getting triggered. Thanks for putting me on the right path, I wanted to blame OpenH264 and that was Wrong(tm).

**Comment by soliton4** [comment]
you are welcome
also writing in a closed issue is maybe not the best idea. feel free to open a new issue next time ;)
