### ISSUE TITLE
clicking on link on by one while switching back in iframe

### ISSUE THREAD

**Issue by kambleashwini** [mbebenita/Broadway#92]
<frameset framespacing="0" border="0" noresize="" frameborder="0" rows="93,73%">
 
   <frame name="top" scrolling="no" noresize="" target="middle" src="mainhead.as">
   </frame >
   <frame name="middle" target="bottom" scrolling="yes" src="welcome.as">
   
         <iframe name="middleFrame" src="department.as" style="width:100%; height:450;" frameborder="0">
                       <iframe src="departmentlistframe.as" width="100%" height="360" frameborder="4" id="listFrame" name="listFrame" marginheight="0" scrolling="AUTO">
			</iframe>
         </iframe>
 </frame >
</frameset>

Details :- 

There are two frames "top" and " middle". "middle" frame contains iframe "middleFrame" and "middleFrame" contains iframe "listFrame".
I want to switch to "top" frame and get all linkstext here and click on first link and switch to frame " middle". here click first link 
and switch to iframe "middleFrame" get all links here and switch to "listFrame" and get all linkstext and navigate back to frame "middle"
and click second link and so on...

Work Details:- 

till now i have succesfully switched to clicked on first link of "top" Frame and then navigate to "middle" frame get all links here.
then switched to "middleFrame" get all links and switched to "listFrame" and get all linktext.

Problem Area:- 

after getting all links from "listFrame" i am not able to switched to frame "middleFrame" and click on second link to move further.
AS i am new selenium user, so m not yet switched to POM and TESTng Framework.

Realated Code :- please do let me know if required..!!

"Thanks in advance..!!!!"

**Comment by mbebenita** [comment]
Appears to be unrelated to Broadway.js, closing.
