### ISSUE TITLE
Sample player doesn't work with video size < 1MB

### ISSUE THREAD

**Issue by fresswolf** [mbebenita/Broadway#97]
There seems to be a problem with smaller videos, no frames are read if the file size of the video is <1MB. Is 1MB used as a buffer somewhere?

**Comment by soliton4** [comment]
the file size is probably not your problem. be aware of the profile limitations. those are probably the cause of your problem.

and yes there is a 1mb input buffer, but that is a limit on the max size for a nal unit

**Comment by fresswolf** [comment]
Thank you for the quick response! I know of the limitations and still got the issue as soon as the file size drops below 1MB. I now found that the decoded frame is always the first frame of the video if the file size is <1MB. To reproduce that behaviour, I reencoded the provided tree.mp4 while limiting it's duration, saving it as mozilla_story.mp4 (overriding) and then analyzing the behaviour with the provided storyDemo.html in firefox.
```
ffmpeg -y -i tree.mp4 -t 25 -r 25 -vcodec libx264 -pass 1 -coder 0 -bf 0 -wpredp 0 -an -x264opts no-cabac:no-weightb -pix_fmt yuv420p mozilla_story.mp4
```
With the above options, the size of mozilla_story.mp4 is 984kb, and when I click the div in storyDemo.html to start playback, the first (green) frame of the video is rendered and rendered again. I assume that the encoding options are correct, because when we slightly use a longer duration with the -t option, so that the file size grows >1MB, the frames are all decoded correctly:
```
ffmpeg -y -i tree.mp4 -t 27 -r 25 -vcodec libx264 -pass 1 -coder 0 -bf 0 -wpredp 0 -an -x264opts no-cabac:no-weightb -pix_fmt yuv420p mozilla_story.mp4
```

Do you have any idea where the problem lies?

**Comment by soliton4** [comment]
interesting problem.
i never had that behaviour but then again i dont use a lot of mp4 files
could you try again with a pure h264 stream?
manualy split into nal units, feed them to player and see how much gets rendered.

**Comment by fresswolf** [comment]
It worked fine with pure h264. As you suspected, the problem was with mp4. I fixed a rounding bug inside mp4.js and created a corresponding pull request. The problem was that the sampleToChunk function returned floating point values for the index value which were then used as array index.
This bug only occurs with sample-to-chunk tables that have only one entry, which somehow was the case only when the file size was below 1MB. With bigger videos, that table length was 2.

**Comment by soliton4** [comment]
thank you very much @fresswolf 
i wish more ppl would share your hands on attitude
feel free to contact me / contribute more in future ;)
